/*******************************************************************************
' MES_MWIPLOTSTS.cs
' Copyright (c) 2013 by Miracom,Inc.
' All rights reserved.
' Generated by MiracomMiddleware 4.0
' Created at 2014-01-06 16:51:29
' Author : Miracom. QMS In Delivery.
' Description : DevTool Xml Query Generator Version 1.0
'
*******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Transactions;
using Miracom.Middleware;

namespace DACrux.MESIF.DSL
{
    public class MES_MWIPLOTSTS : Miracom.Middleware.QueryComponent
    {
        public MES_MWIPLOTSTS()
        {
            string connectID = string.Empty;
            try
            {
                connectID = System.Configuration.ConfigurationManager.AppSettings["MES_CONNECT_ID"];
                if (connectID.Equals(string.Empty))
                {
                    throw new Exception("The connect ID nothing. Please, check app.config.");
                }
                this.InitQueryComponent(connectID, "MES_MWIPLOTSTS.xml");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public MES_MWIPLOTSTS(string connectID)
        {
            try
            {
                this.InitQueryComponent(connectID, "MES_MWIPLOTSTS.xml");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


/// Appand Query ID's Function
        public DataTable SelectCustomerList()
        {
            try
            {
                return this.GetDataTable("SELECT_CUSTOMER_LIST", null, null);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectPrdFamilyList()
        {
            try
            {
                return this.GetDataTable("SELECT_PRD_FAMILY_LIST", null, null);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectPkgList()
        {
            try
            {
                return this.GetDataTable("SELECT_PKG_LIST", null, null);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectMatIdList(string productfamily, string customername)
        {
            try
            {
                return this.GetDataTable("SELECT_MAT_ID_LIST", null, new string[] {productfamily, customername});
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectProcessList(string productfamily, string customername)
        {
            try
            {
                return this.GetDataTable("SELECT_PROCESS_LIST", null, new string[] {productfamily, customername});
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectStepList(string process_plan)
        {
            try
            {
                return this.GetDataTable("SELECT_STEP_LIST", null, new string[] {process_plan});
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectLotListByCustomer(string customer)
        {
            try
            {
                return this.GetDataTable("SELECT_LOT_LIST_BY_CUSTOMER", null, new string[] { customer });
            }
            catch (Exception ex)
            {
                
                throw ex;
            }
        }

        public DataTable SelectLotInfo(string lot_id, string equip_id)
        {
            try
            {
                return this.GetDataTable("SELECT_LOT_INFO_01", null, new string[] { lot_id, equip_id });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public DataTable SelectLotByStartRes(string factory, string equip_id)
        {
            try
            {
                return this.GetDataTable("SELECT_LOT_BY_START_RES_ID", null, new string[] { factory, equip_id });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public DataTable SelectLotBaseInfo(string LOT_ID)
        {
            try
            {
                return this.GetDataTable("SELECT_LOT_BASE_INFO_01", null, new string[] { LOT_ID });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public DataTable SelectTankNumList(string LOT_ID)
        {
            try
            {
                return this.GetDataTable("SELECT_TANKNUM_LIST", null, new string[] { LOT_ID });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        public DataTable SelectLotInMat(string strLotList, string MatGrp, string MatID)
        {
            try
            {
                if(string.IsNullOrEmpty(MatID) == false)
                    return this.GetDataTable("SELECT_LOT_LIST_IN_MAT", new string[] { strLotList }, new string[] { MatID });
                else
                    return this.GetDataTable("SELECT_LOT_LIST_IN_MAT_01", new string[] { strLotList }, new string[] { MatGrp });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        public DataTable SelectEqpBaseLotIdList(string sEqpID)
        {
            throw new NotImplementedException();
        }

        public DataTable SelectParentLotID(string sSubLotID)
        {
            throw new NotImplementedException();
        }

        public DataTable SelectSubLotID(string sParentLotID)
        {
            throw new NotImplementedException();
        }

        // RMS »ç¿ë
        public DataTable SelectLotList(
            string factory,
            string matId,
            string oper
            )
        {
            try
            {
                return this.GetDataTable("SELECT_LOT_LIST_RMS", null, new string[] { factory, matId, oper });
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    } //EndOfClass
} //EndOfNamespace
