/*******************************************************************************
' MES_MRASRESOPR.cs
' Copyright (c) 2013 by Miracom,Inc.
' All rights reserved.
' Generated by MiracomMiddleware 4.0
' Created at 2014-01-06 16:52:04
' Author : Miracom. QMS In Delivery.
' Description : DevTool Xml Query Generator Version 1.0
'
*******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Transactions;
using Miracom.Middleware;

namespace DACrux.MESIF.DSL
{
    public class MES_MRASRESOPR : Miracom.Middleware.QueryComponent
    {
        public MES_MRASRESOPR()
        {
            string connectID = string.Empty;
            try
            {
                connectID = System.Configuration.ConfigurationManager.AppSettings["MES_CONNECT_ID"];
                if (connectID.Equals(string.Empty))
                {
                    throw new Exception("The connect ID nothing. Please, check app.config.");
                }
                this.InitQueryComponent(connectID, "MES_MRASRESOPR.xml");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


/// Appand Query ID's Function
        public DataTable SelectOperEquipList(string sFactory, string sOper)
        {
            try
            {
                return this.GetDataTable("SELECT_OPER_EQP_ID_LIST", null, new string[] { sFactory, sOper });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectOperRESList(string sFactory, string sOper)
        {
            try
            {
                return this.GetDataTable("SELECT_OPER_RES", null, new string[] { sFactory, sOper });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }



    } //EndOfClass
} //EndOfNamespace
