/*******************************************************************************
' MES_MWIPFLWOPR.cs
' Copyright (c) 2013 by Miracom,Inc.
' All rights reserved.
' Generated by MiracomMiddleware 4.0
' Created at 2014-02-18 18:11:26
' Author : Miracom. QMS In Delivery.
' Description : DevTool Xml Query Generator Version 1.0
'
*******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Transactions;
using Miracom.Middleware;

namespace DACrux.MESIF.DSL
{
    public class MES_MWIPFLWOPR : Miracom.Middleware.QueryComponent
    {
        public MES_MWIPFLWOPR()
        {
            string connectID = string.Empty;
            try
            {
                connectID = System.Configuration.ConfigurationManager.AppSettings["MES_CONNECT_ID"];
                if (connectID.Equals(string.Empty))
                {
                    throw new Exception("The connect ID nothing. Please, check app.config.");
                }
                this.InitQueryComponent(connectID, "MES_MWIPFLWOPR.xml");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


/// Appand Query ID's Function
        public DataTable SelectFlowList()
        {
            try
            {
                return this.GetDataTable("SELECT_FLOW_LIST", null, null);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectOprList()
        {
            try
            {
                return this.GetDataTable("SELECT_OPR_LIST", null, null);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectOperByflow(string flow)
        {
            try
            {
                if (flow.Trim() == string.Empty || flow.Trim() == "*") flow = "ALL";

                return this.GetDataTable("SELECT_OPER_BYFLOW", null, new string[] {flow});
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // ----------------------------------------------------------------------------------------------------------------------
        // RMS »ç¿ë
        public System.Data.DataTable SELECT_NEXT_OPER(
            string factory,
            string flow,
            string oper
            )
        {
            try
            {
                return this.GetDataTable("SELECT_NEXT_OPER", null, new string[] { factory, flow, oper });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectOperByMatId(
            string factory,
            string matId
            )
        {
            return this.GetDataTable("SELECT_OPER_BY_MATID", null, new string[] { factory, matId });
        }

        public DataTable SelectOperByMatId(
            string factory,
            string matId,
            string searchOper
            )
        {
            if (searchOper == string.Empty)
            {
                return this.GetDataTable("SELECT_OPER_BY_MATID", null, new string[] { factory, matId });
            }

            return this.GetDataTable("SELECT_OPER_BY_MATID_02", null, new string[] { factory, matId, searchOper });
        }       

        // ----------------------------------------------------------------------------------------------------------------------

    } //EndOfClass
} //EndOfNamespace
