/*******************************************************************************
' MES_CWIPCTLDEF.cs
' Copyright (c) 2013 by Miracom,Inc.
' All rights reserved.
' Generated by MiracomMiddleware 4.0
' Created at 2014-01-06 16:52:04
' Author : Miracom. QMS In Delivery.
' Description : DevTool Xml Query Generator Version 1.0
'
*******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Transactions;
using Miracom.Middleware;

namespace DACrux.MESIF.DSL
{
    public class MES_CWIPCTLDEF : Miracom.Middleware.QueryComponent
    {
        public MES_CWIPCTLDEF()
        {
            string connectID = string.Empty;
            try
            {
                connectID = System.Configuration.ConfigurationManager.AppSettings["MES_CONNECT_ID"];
                if (connectID.Equals(string.Empty))
                {
                    throw new Exception("The connect ID nothing. Please, check app.config.");
                }
                this.InitQueryComponent(connectID, "MES_CWIPCTLDEF.xml");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


/// Appand Query ID's Function
        public DataTable SelectUsageList(string sFactory)
        {
            try
            {
                return this.GetDataTable("SELECT_USAGE_LIST", null, new string[] { sFactory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectCustomerList(string sFactory)
        {
            try
            {
                return this.GetDataTable("SELECT_CUSTOMER_LIST", null, new string[] { sFactory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectLotType(string sFactory)
        {
            try
            {
                return this.GetDataTable("SELECT_LOT_TYPE", null, new string[] { sFactory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectEndUser(string sFactory)
        {
            try
            {
                return this.GetDataTable("SELECT_END_USER", null, new string[] { sFactory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectProductTypeList(string factory)
        {
            try
            {
                return this.GetDataTable("SELECT_MAT_TYPE_LIST", null, new string[] { factory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectProductGroupList(string factory, string prod_type)
        {
            try
            {
                if(string.IsNullOrEmpty(prod_type) == true)
                    return this.GetDataTable("SELECT_MAT_GROUP_LIST_01", null, new string[] { factory });
                else
                    return this.GetDataTable("SELECT_MAT_GROUP_LIST", null, new string[] { factory, prod_type });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectMatList(string sDynSQL1, string sDynSQL2)
        {
            try
            {
                return this.GetDataTable("SELECT_MAT_LIST_COND", new string[] { sDynSQL1, sDynSQL2 }, null);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

    } //EndOfClass
} //EndOfNamespace
