/*******************************************************************************
' MES_MRASRESDEF.cs
' Copyright (c) 2013 by Miracom,Inc.
' All rights reserved.
' Generated by MiracomMiddleware 4.0
' Created at 2014-01-06 16:52:04
' Author : Miracom. QMS In Delivery.
' Description : DevTool Xml Query Generator Version 1.0
'
*******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Transactions;
using Miracom.Middleware;

namespace DACrux.MESIF.DSL
{
    public class MES_MRASRESDEF : Miracom.Middleware.QueryComponent
    {
        public MES_MRASRESDEF()
        {
            string connectID = string.Empty;
            try
            {
                connectID = System.Configuration.ConfigurationManager.AppSettings["MES_CONNECT_ID"];
                if (connectID.Equals(string.Empty))
                {
                    throw new Exception("The connect ID nothing. Please, check app.config.");
                }
                this.InitQueryComponent(connectID, "MES_MRASRESDEF.xml");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


/// Appand Query ID's Function
        public DataTable SelectEqpIdList(string eqpid, string eqptype)
        {
            try
            {
                if (eqptype.Trim() == string.Empty) eqptype = "ALL";
                if (eqpid.Trim() == string.Empty) eqpid = "ALL";
                return this.GetDataTable("SELECT_EQP_ID_LIST", null, new string[] {eqptype, eqpid});
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectEqtypeList()
        {
            try
            {
                return this.GetDataTable("SELECT_EQTYPE_LIST", null, null);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectEqInfo(string factory, string res_id)
        {
            try
            {
                return this.GetDataTable("SELECT_EQP_INFO", null, new string[] { factory, res_id });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectResourceModel(
            string factory, 
            string maker
            )
        {
            try
            {
                return this.GetDataTable("SELECT_RES_MODEL", null, new string[] { factory, maker });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectResourceModel(
            string factory
            )
        {
            try
            {
                return this.GetDataTable("SELECT_RES_MODEL_02", null, new string[] { factory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectResourceModelByOperGroup(
            string factory,
            string operGroup
            )
        {
            try
            {
                return this.GetDataTable("SELECT_RES_MODEL_BY_OPERGROUP", null, new string[] { factory, operGroup });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectResourceList(
            string factory,
            string resourceModel
            )
        {
            try
            {
                return this.GetDataTable("SELECT_RES_LIST", null, new string[] { factory, resourceModel });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectResourceDetailList(
            string factory,
            string operGroup,
            string resourceModel
            )
        {
            try
            {
                return this.GetDataTable("SELECT_RES_DETAIL_LIST", null, new string[] { factory, operGroup, resourceModel });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public DataTable SelectResourceDetailListByMaker(
            string factory,
            string maker,
            string resourceModel
            )
        {
            try
            {
                return this.GetDataTable("SELECT_RES_DETAIL_LIST_BY_MAKER", null, new string[] { factory, maker, resourceModel });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }


        public DataTable SelectResourceMaker(string factory)
        {
            try
            {
                return this.GetDataTable("SELECT_RES_MAKER", null, new string[] { factory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public System.Data.DataTable SelectModelInfo(string factory, string sResModel)
        {
            try
            {
                return this.GetDataTable("SELECT_MODEL_INFO", null, new string[] { factory, sResModel });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public System.Data.DataTable SelectOperGroup(
            string factory
            )
        {
            try
            {
                return this.GetDataTable("SELECT_OPER_GROUP", null, new string[] { factory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

       
        // ----------------------------------------------------------------------------------------------------------------------
        // RMS »ç¿ë
        public System.Data.DataTable SELECT_RES_STATUS(string factory, string strResID)
        {
            try
            {
                return this.GetDataTable("SELECT_RES_STATUS_01", null, new string[] { factory, strResID });
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
            }        
        }

        public System.Data.DataTable GetRasCommon(
            string factory,
            List<string> arrResPartList
            )
        {
            string strPartList = string.Empty;

            try
            {
                strPartList = string.Format("{0}", string.Join("", arrResPartList.ToArray()));
                return this.GetDataTable("SELECT_RES_COMMON", new string[] { strPartList }, new string[] { factory });
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
            }
        }

        // ----------------------------------------------------------------------------------------------------------------------

    } //EndOfClass
} //EndOfNamespace
