-- One-time migration of empty, newly created TQP_GDS_* tables only.
-- Do not rerun. Legacy TQP business tables are never altered.
-- CREATE/UPDATE columns follow existing TQP DATE + VARCHAR2(30 CHAR) conventions.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET ECHO ON FEEDBACK ON

-- Type conversion is allowed only before any Map/Chain data is inserted.
DECLARE
    v_rows NUMBER;
BEGIN
    FOR t IN (SELECT TABLE_NAME FROM DBA_TABLES
               WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%') LOOP
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM DMSMGR.' || t.TABLE_NAME INTO v_rows;
        IF v_rows <> 0 THEN
            RAISE_APPLICATION_ERROR(-20001, t.TABLE_NAME || ' contains data');
        END IF;
    END LOOP;
END;
/

-- Resume after ORA-01442: first two MAP_REV column renames already succeeded.
ALTER TABLE DMSMGR.TQP_GDS_MAP_REV MODIFY (CREATE_USER VARCHAR2(30 CHAR), CREATE_TIME DATE DEFAULT SYSDATE);
ALTER TABLE DMSMGR.TQP_GDS_MAP_REV ADD (UPDATE_USER VARCHAR2(30 CHAR), UPDATE_TIME DATE);

ALTER TABLE DMSMGR.TQP_GDS_MAP_ACTIVE RENAME COLUMN UPDATED_BY TO UPDATE_USER;
ALTER TABLE DMSMGR.TQP_GDS_MAP_ACTIVE RENAME COLUMN UPDATED_AT TO UPDATE_TIME;
ALTER TABLE DMSMGR.TQP_GDS_MAP_ACTIVE MODIFY (UPDATE_USER VARCHAR2(30 CHAR), UPDATE_TIME DATE DEFAULT SYSDATE);
ALTER TABLE DMSMGR.TQP_GDS_MAP_ACTIVE ADD (CREATE_USER VARCHAR2(30 CHAR), CREATE_TIME DATE DEFAULT SYSDATE NOT NULL);

ALTER TABLE DMSMGR.TQP_GDS_IMPORT_JOB RENAME COLUMN CREATED_AT TO CREATE_TIME;
ALTER TABLE DMSMGR.TQP_GDS_IMPORT_JOB RENAME COLUMN UPDATED_AT TO UPDATE_TIME;
ALTER TABLE DMSMGR.TQP_GDS_IMPORT_JOB MODIFY (CREATE_TIME DATE DEFAULT SYSDATE, UPDATE_TIME DATE DEFAULT SYSDATE);
ALTER TABLE DMSMGR.TQP_GDS_IMPORT_JOB ADD (CREATE_USER VARCHAR2(30 CHAR), UPDATE_USER VARCHAR2(30 CHAR));

ALTER TABLE DMSMGR.TQP_GDS_IMPORT_BATCH RENAME COLUMN COMMITTED_AT TO COMMIT_TIME;
ALTER TABLE DMSMGR.TQP_GDS_IMPORT_BATCH MODIFY (COMMIT_TIME DATE DEFAULT SYSDATE);

ALTER TABLE DMSMGR.TQP_GDS_CHAIN RENAME COLUMN CREATED_BY TO CREATE_USER;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN RENAME COLUMN CREATED_AT TO CREATE_TIME;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN RENAME COLUMN RETIRED_AT TO RETIRE_TIME;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN MODIFY (CREATE_USER VARCHAR2(30 CHAR), CREATE_TIME DATE DEFAULT SYSDATE, RETIRE_TIME DATE);
ALTER TABLE DMSMGR.TQP_GDS_CHAIN ADD (UPDATE_USER VARCHAR2(30 CHAR), UPDATE_TIME DATE);

ALTER TABLE DMSMGR.TQP_GDS_CHAIN_VER RENAME COLUMN CREATED_BY TO CREATE_USER;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_VER RENAME COLUMN CREATED_AT TO CREATE_TIME;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_VER MODIFY (CREATE_USER VARCHAR2(30 CHAR), CREATE_TIME DATE DEFAULT SYSDATE);
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_VER ADD (UPDATE_USER VARCHAR2(30 CHAR), UPDATE_TIME DATE);

-- An edit log row is an immutable record of an action, so it has creation metadata.
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_EDIT RENAME COLUMN EDITED_BY TO CREATE_USER;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_EDIT RENAME COLUMN EDITED_AT TO CREATE_TIME;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_EDIT MODIFY (CREATE_USER VARCHAR2(30 CHAR), CREATE_TIME DATE DEFAULT SYSDATE);

EXIT
