-- DMSMGR / MESMGR: GDS Chain schema, phase 2.
-- Run after 2026-10-01_tqp_gds_map_schema.sql. Creates new TQP_GDS_* objects only.
-- Status/current-version changes must set UPDATE_TIME/UPDATE_USER in the Service transaction.
-- Immutable member/rule rows omit audit columns to avoid per-element storage overhead.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET ECHO OFF FEEDBACK ON

CREATE TABLE DMSMGR.TQP_GDS_CHAIN (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    CHAIN_ID VARCHAR2(36 BYTE) NOT NULL,
    CHAIN_CODE VARCHAR2(32 CHAR) NOT NULL,
    CHAIN_STATUS VARCHAR2(20 BYTE) DEFAULT 'ACTIVE' NOT NULL,
    CREATE_USER VARCHAR2(30 BYTE),
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER VARCHAR2(30 BYTE),
    UPDATE_TIME DATE,
    RETIRE_TIME DATE,
    CONSTRAINT PK_GDS_CHAIN PRIMARY KEY (MAP_REVISION_ID, CHAIN_ID),
    CONSTRAINT UQ_GDS_CHAIN_CODE UNIQUE (MAP_REVISION_ID, CHAIN_CODE),
    CONSTRAINT FK_GDS_CHAIN_REV FOREIGN KEY (MAP_REVISION_ID)
        REFERENCES DMSMGR.TQP_GDS_MAP_REV (MAP_REVISION_ID),
    CONSTRAINT CK_GDS_CHAIN_STATUS CHECK (CHAIN_STATUS IN ('ACTIVE','RETIRED'))
);

CREATE TABLE DMSMGR.TQP_GDS_CHAIN_VER (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    CHAIN_ID VARCHAR2(36 BYTE) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    CHAIN_NAME VARCHAR2(200 CHAR) NOT NULL,
    COLOR_ARGB NUMBER(10) NOT NULL,
    APPLY_LAYER_RULES NUMBER(1) DEFAULT 0 NOT NULL,
    CELL_SIZE NUMBER(18,4) NOT NULL,
    VERSION_STATUS VARCHAR2(20 BYTE) DEFAULT 'DRAFT' NOT NULL,
    IS_CURRENT NUMBER(1) DEFAULT 0 NOT NULL,
    CREATE_USER VARCHAR2(30 BYTE),
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER VARCHAR2(30 BYTE),
    UPDATE_TIME DATE,
    CONSTRAINT PK_GDS_CHAIN_VER PRIMARY KEY (MAP_REVISION_ID, CHAIN_ID, VERSION_NO),
    CONSTRAINT FK_GDS_CHAIN_VER_MASTER FOREIGN KEY (MAP_REVISION_ID, CHAIN_ID)
        REFERENCES DMSMGR.TQP_GDS_CHAIN (MAP_REVISION_ID, CHAIN_ID),
    CONSTRAINT CK_GDS_CHAIN_VER_NO CHECK (VERSION_NO > 0),
    CONSTRAINT CK_GDS_CHAIN_VER_STATUS CHECK (VERSION_STATUS IN ('DRAFT','READY','SUPERSEDED')),
    CONSTRAINT CK_GDS_CHAIN_VER_RULES CHECK (APPLY_LAYER_RULES IN (0,1)),
    CONSTRAINT CK_GDS_CHAIN_VER_CURRENT CHECK (IS_CURRENT IN (0,1) AND (IS_CURRENT = 0 OR VERSION_STATUS = 'READY')),
    CONSTRAINT CK_GDS_CHAIN_VER_CELL CHECK (CELL_SIZE > 0)
);

-- Only one current version per Chain. All-null expression keys omit other versions.
CREATE UNIQUE INDEX DMSMGR.UX_GDS_CHAIN_CURRENT ON DMSMGR.TQP_GDS_CHAIN_VER (
    CASE WHEN IS_CURRENT = 1 THEN MAP_REVISION_ID END,
    CASE WHEN IS_CURRENT = 1 THEN CHAIN_ID END
);

CREATE TABLE DMSMGR.TQP_GDS_CHAIN_MEMBER (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    CHAIN_ID VARCHAR2(36 BYTE) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    PLACED_ELEMENT_ID VARCHAR2(1024 BYTE) NOT NULL,
    ROLE_CODE VARCHAR2(10 BYTE) NOT NULL,
    INCLUSION_SOURCE VARCHAR2(10 BYTE) NOT NULL,
    MARKER_X BINARY_DOUBLE,
    MARKER_Y BINARY_DOUBLE,
    CONSTRAINT PK_GDS_CHAIN_MEMBER PRIMARY KEY
        (MAP_REVISION_ID, CHAIN_ID, VERSION_NO, PLACED_ELEMENT_ID),
    CONSTRAINT FK_GDS_CHAIN_MEMBER_VER FOREIGN KEY
        (MAP_REVISION_ID, CHAIN_ID, VERSION_NO)
        REFERENCES DMSMGR.TQP_GDS_CHAIN_VER (MAP_REVISION_ID, CHAIN_ID, VERSION_NO),
    CONSTRAINT FK_GDS_CHAIN_MEMBER_EL FOREIGN KEY
        (MAP_REVISION_ID, PLACED_ELEMENT_ID)
        REFERENCES DMSMGR.TQP_GDS_PLACED_EL (MAP_REVISION_ID, PLACED_ELEMENT_ID),
    CONSTRAINT CK_GDS_CHAIN_MEMBER_ROLE CHECK (ROLE_CODE IN ('INPUT','OUTPUT','MEMBER')),
    CONSTRAINT CK_GDS_CHAIN_MEMBER_SRC CHECK (INCLUSION_SOURCE IN ('TRACE','MANUAL','ENDPOINT')),
    CONSTRAINT CK_GDS_CHAIN_MEMBER_MARKER CHECK
        ((ROLE_CODE IN ('INPUT','OUTPUT') AND MARKER_X IS NOT NULL AND MARKER_Y IS NOT NULL)
         OR (ROLE_CODE = 'MEMBER' AND MARKER_X IS NULL AND MARKER_Y IS NULL))
);

-- Limit INPUT and OUTPUT to one row each per Chain version, without limiting MEMBER rows.
CREATE UNIQUE INDEX DMSMGR.UX_GDS_CHAIN_ENDPOINT ON DMSMGR.TQP_GDS_CHAIN_MEMBER (
    CASE WHEN ROLE_CODE IN ('INPUT','OUTPUT') THEN MAP_REVISION_ID END,
    CASE WHEN ROLE_CODE IN ('INPUT','OUTPUT') THEN CHAIN_ID END,
    CASE WHEN ROLE_CODE IN ('INPUT','OUTPUT') THEN VERSION_NO END,
    CASE WHEN ROLE_CODE IN ('INPUT','OUTPUT') THEN ROLE_CODE END
);
CREATE INDEX DMSMGR.IX_GDS_CHAIN_MEMBER_EL ON DMSMGR.TQP_GDS_CHAIN_MEMBER
    (MAP_REVISION_ID, PLACED_ELEMENT_ID, CHAIN_ID, VERSION_NO);

CREATE TABLE DMSMGR.TQP_GDS_CHAIN_LAYER (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    CHAIN_ID VARCHAR2(36 BYTE) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    LAYER_ID NUMBER(10) NOT NULL,
    CONSTRAINT PK_GDS_CHAIN_LAYER PRIMARY KEY (MAP_REVISION_ID, CHAIN_ID, VERSION_NO, LAYER_ID),
    CONSTRAINT FK_GDS_CHAIN_LAYER_VER FOREIGN KEY (MAP_REVISION_ID, CHAIN_ID, VERSION_NO)
        REFERENCES DMSMGR.TQP_GDS_CHAIN_VER (MAP_REVISION_ID, CHAIN_ID, VERSION_NO),
    CONSTRAINT FK_GDS_CHAIN_LAYER_MAP FOREIGN KEY (MAP_REVISION_ID, LAYER_ID)
        REFERENCES DMSMGR.TQP_GDS_LAYER (MAP_REVISION_ID, LAYER_ID)
);

CREATE TABLE DMSMGR.TQP_GDS_CHAIN_RULE (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    CHAIN_ID VARCHAR2(36 BYTE) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    FIRST_LAYER_ID NUMBER(10) NOT NULL,
    SECOND_LAYER_ID NUMBER(10) NOT NULL,
    TOLERANCE BINARY_DOUBLE NOT NULL,
    CONSTRAINT PK_GDS_CHAIN_RULE PRIMARY KEY
        (MAP_REVISION_ID, CHAIN_ID, VERSION_NO, FIRST_LAYER_ID, SECOND_LAYER_ID),
    CONSTRAINT FK_GDS_CHAIN_RULE_VER FOREIGN KEY (MAP_REVISION_ID, CHAIN_ID, VERSION_NO)
        REFERENCES DMSMGR.TQP_GDS_CHAIN_VER (MAP_REVISION_ID, CHAIN_ID, VERSION_NO),
    CONSTRAINT FK_GDS_CHAIN_RULE_L1 FOREIGN KEY (MAP_REVISION_ID, FIRST_LAYER_ID)
        REFERENCES DMSMGR.TQP_GDS_LAYER (MAP_REVISION_ID, LAYER_ID),
    CONSTRAINT FK_GDS_CHAIN_RULE_L2 FOREIGN KEY (MAP_REVISION_ID, SECOND_LAYER_ID)
        REFERENCES DMSMGR.TQP_GDS_LAYER (MAP_REVISION_ID, LAYER_ID),
    CONSTRAINT CK_GDS_CHAIN_RULE_PAIR CHECK (FIRST_LAYER_ID <= SECOND_LAYER_ID),
    CONSTRAINT CK_GDS_CHAIN_RULE_TOL CHECK (TOLERANCE >= 0)
);

CREATE TABLE DMSMGR.TQP_GDS_CHAIN_EDIT (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    CHAIN_ID VARCHAR2(36 BYTE) NOT NULL,
    VERSION_NO NUMBER(10) NOT NULL,
    EDIT_SEQ NUMBER(12) NOT NULL,
    PLACED_ELEMENT_ID VARCHAR2(1024 BYTE) NOT NULL,
    ACTION_CODE VARCHAR2(10 BYTE) NOT NULL,
    BATCH_EDIT_ID VARCHAR2(36 BYTE),
    CREATE_USER VARCHAR2(30 BYTE),
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_GDS_CHAIN_EDIT PRIMARY KEY (MAP_REVISION_ID, CHAIN_ID, VERSION_NO, EDIT_SEQ),
    CONSTRAINT FK_GDS_CHAIN_EDIT_VER FOREIGN KEY (MAP_REVISION_ID, CHAIN_ID, VERSION_NO)
        REFERENCES DMSMGR.TQP_GDS_CHAIN_VER (MAP_REVISION_ID, CHAIN_ID, VERSION_NO),
    CONSTRAINT FK_GDS_CHAIN_EDIT_EL FOREIGN KEY (MAP_REVISION_ID, PLACED_ELEMENT_ID)
        REFERENCES DMSMGR.TQP_GDS_PLACED_EL (MAP_REVISION_ID, PLACED_ELEMENT_ID),
    CONSTRAINT CK_GDS_CHAIN_EDIT_ACTION CHECK (ACTION_CODE IN ('ADD','EXCLUDE','RESTORE')),
    CONSTRAINT CK_GDS_CHAIN_EDIT_SEQ CHECK (EDIT_SEQ > 0)
);

CREATE INDEX DMSMGR.IX_GDS_CHAIN_EDIT_EL ON DMSMGR.TQP_GDS_CHAIN_EDIT
    (MAP_REVISION_ID, PLACED_ELEMENT_ID, CHAIN_ID, VERSION_NO);

EXIT
