-- DMSMGR: GDS Map FK 삭제 규칙 조정 (CLAUDE-017, 2026-10-02)
-- 문제: 2026-10-02_tqp_gds_schema_device.sql에서 모든 FK를 ON DELETE CASCADE로 만들었더니,
--       큰 테이블 사이 FK(SOURCE -> PLACED, PLACED -> CHAIN_MEMBER / CHAIN_EDIT 등)에서 부모 행마다 내부 DELETE가 실행되어
--       샘플 1 Device(SOURCE 636,970 / PLACED 605,080) 삭제가 10분을 넘겼다(latch: shared pool 대기).
-- 조정: 행이 많은 테이블 사이의 FK 7개는 CASCADE를 빼고(일반 FK), BSL GdsMapImport.DeleteMap이 자식부터 직접 지운다.
--       CASCADE 유지: TQP_GDS_MAP(헤더 1건) -> LAYER / SOURCE_EL / IMPORT_JOB / CHAIN, IMPORT_JOB -> IMPORT_BATCH,
--                     CHAIN -> CHAIN_VER -> CHAIN_MEMBER / CHAIN_LAYER / CHAIN_RULE / CHAIN_EDIT (Chain은 행 수가 적음)
-- 삭제 순서(BSL): CHAIN(-> Chain 하위 CASCADE) -> PLACED_EL -> SOURCE_EL -> MAP(-> LAYER / IMPORT_JOB -> IMPORT_BATCH CASCADE)
-- 데이터는 유지한다. 재실행하면 DROP CONSTRAINT에서 이미 바뀐 FK도 다시 만든다(같은 결과).
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET ECHO OFF FEEDBACK ON

ALTER TABLE DMSMGR.TQP_GDS_PLACED_EL DROP CONSTRAINT FK_GDS_PLACED_SOURCE;
ALTER TABLE DMSMGR.TQP_GDS_PLACED_EL ADD CONSTRAINT FK_GDS_PLACED_SOURCE FOREIGN KEY (FACTORY, DEVICE_ID, SOURCE_ELEMENT_ID)
    REFERENCES DMSMGR.TQP_GDS_SOURCE_EL (FACTORY, DEVICE_ID, SOURCE_ELEMENT_ID);

ALTER TABLE DMSMGR.TQP_GDS_PLACED_EL DROP CONSTRAINT FK_GDS_PLACED_LAYER;
ALTER TABLE DMSMGR.TQP_GDS_PLACED_EL ADD CONSTRAINT FK_GDS_PLACED_LAYER FOREIGN KEY (FACTORY, DEVICE_ID, LAYER_ID)
    REFERENCES DMSMGR.TQP_GDS_LAYER (FACTORY, DEVICE_ID, LAYER_ID);

ALTER TABLE DMSMGR.TQP_GDS_CHAIN_MEMBER DROP CONSTRAINT FK_GDS_CHAIN_MEMBER_EL;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_MEMBER ADD CONSTRAINT FK_GDS_CHAIN_MEMBER_EL FOREIGN KEY (FACTORY, DEVICE_ID, PLACED_ELEMENT_ID)
    REFERENCES DMSMGR.TQP_GDS_PLACED_EL (FACTORY, DEVICE_ID, PLACED_ELEMENT_ID);

ALTER TABLE DMSMGR.TQP_GDS_CHAIN_EDIT DROP CONSTRAINT FK_GDS_CHAIN_EDIT_EL;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_EDIT ADD CONSTRAINT FK_GDS_CHAIN_EDIT_EL FOREIGN KEY (FACTORY, DEVICE_ID, PLACED_ELEMENT_ID)
    REFERENCES DMSMGR.TQP_GDS_PLACED_EL (FACTORY, DEVICE_ID, PLACED_ELEMENT_ID);

ALTER TABLE DMSMGR.TQP_GDS_CHAIN_LAYER DROP CONSTRAINT FK_GDS_CHAIN_LAYER_MAP;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_LAYER ADD CONSTRAINT FK_GDS_CHAIN_LAYER_MAP FOREIGN KEY (FACTORY, DEVICE_ID, LAYER_ID)
    REFERENCES DMSMGR.TQP_GDS_LAYER (FACTORY, DEVICE_ID, LAYER_ID);

ALTER TABLE DMSMGR.TQP_GDS_CHAIN_RULE DROP CONSTRAINT FK_GDS_CHAIN_RULE_L1;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_RULE ADD CONSTRAINT FK_GDS_CHAIN_RULE_L1 FOREIGN KEY (FACTORY, DEVICE_ID, FIRST_LAYER_ID)
    REFERENCES DMSMGR.TQP_GDS_LAYER (FACTORY, DEVICE_ID, LAYER_ID);

ALTER TABLE DMSMGR.TQP_GDS_CHAIN_RULE DROP CONSTRAINT FK_GDS_CHAIN_RULE_L2;
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_RULE ADD CONSTRAINT FK_GDS_CHAIN_RULE_L2 FOREIGN KEY (FACTORY, DEVICE_ID, SECOND_LAYER_ID)
    REFERENCES DMSMGR.TQP_GDS_LAYER (FACTORY, DEVICE_ID, LAYER_ID);

-- FK 검사 인덱스: CHAIN_LAYER / CHAIN_RULE의 Layer FK 열이 기존 인덱스 앞부분에 없어 Layer 삭제 시 전체 검색이 된다(행 수는 적음).
CREATE INDEX DMSMGR.IX_GDS_CHAIN_LAYER_LY ON DMSMGR.TQP_GDS_CHAIN_LAYER (FACTORY, DEVICE_ID, LAYER_ID);
CREATE INDEX DMSMGR.IX_GDS_CHAIN_RULE_L1 ON DMSMGR.TQP_GDS_CHAIN_RULE (FACTORY, DEVICE_ID, FIRST_LAYER_ID);
CREATE INDEX DMSMGR.IX_GDS_CHAIN_RULE_L2 ON DMSMGR.TQP_GDS_CHAIN_RULE (FACTORY, DEVICE_ID, SECOND_LAYER_ID);

EXIT
