-- Final alignment with existing TQP user IDs: VARCHAR2(30 BYTE).
-- Run once, while the six new tables are empty. Existing business tables are untouched.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET FEEDBACK ON
DECLARE
    v_rows NUMBER;
BEGIN
    FOR t IN (SELECT TABLE_NAME FROM DBA_TABLES
               WHERE OWNER = 'DMSMGR' AND TABLE_NAME IN
               ('TQP_GDS_MAP_REV','TQP_GDS_MAP_ACTIVE','TQP_GDS_IMPORT_JOB',
                'TQP_GDS_CHAIN','TQP_GDS_CHAIN_VER','TQP_GDS_CHAIN_EDIT')) LOOP
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM DMSMGR.' || t.TABLE_NAME INTO v_rows;
        IF v_rows <> 0 THEN
            RAISE_APPLICATION_ERROR(-20001, t.TABLE_NAME || ' contains data');
        END IF;
    END LOOP;
END;
/

ALTER TABLE DMSMGR.TQP_GDS_MAP_REV MODIFY (CREATE_USER VARCHAR2(30 BYTE), UPDATE_USER VARCHAR2(30 BYTE));
ALTER TABLE DMSMGR.TQP_GDS_MAP_ACTIVE MODIFY (CREATE_USER VARCHAR2(30 BYTE), UPDATE_USER VARCHAR2(30 BYTE));
ALTER TABLE DMSMGR.TQP_GDS_IMPORT_JOB MODIFY (CREATE_USER VARCHAR2(30 BYTE), UPDATE_USER VARCHAR2(30 BYTE));
ALTER TABLE DMSMGR.TQP_GDS_CHAIN MODIFY (CREATE_USER VARCHAR2(30 BYTE), UPDATE_USER VARCHAR2(30 BYTE));
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_VER MODIFY (CREATE_USER VARCHAR2(30 BYTE), UPDATE_USER VARCHAR2(30 BYTE));
ALTER TABLE DMSMGR.TQP_GDS_CHAIN_EDIT MODIFY (CREATE_USER VARCHAR2(30 BYTE));
EXIT
