-- Read-only check of legacy TQP audit columns and new GDS audit columns.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET PAGESIZE 200 LINESIZE 220 FEEDBACK OFF
COLUMN COLUMN_NAME FORMAT A26
COLUMN DATA_TYPE FORMAT A18
COLUMN EXAMPLES FORMAT A100
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, COUNT(*) TABLE_COUNT,
       LISTAGG(TABLE_NAME, ', ') WITHIN GROUP (ORDER BY TABLE_NAME) AS EXAMPLES
  FROM DBA_TAB_COLUMNS
 WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_%'
   AND TABLE_NAME NOT LIKE 'TQP_GDS_%'
   AND (COLUMN_NAME LIKE '%TIME' OR COLUMN_NAME LIKE '%USER'
        OR COLUMN_NAME LIKE '%FLAG' OR COLUMN_NAME LIKE '%STATUS')
 GROUP BY COLUMN_NAME, DATA_TYPE, DATA_LENGTH
 ORDER BY COLUMN_NAME, DATA_TYPE, DATA_LENGTH;

COLUMN TABLE_NAME FORMAT A28
COLUMN NULLABLE FORMAT A8
COLUMN DATA_DEFAULT FORMAT A35
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT
  FROM DBA_TAB_COLUMNS
 WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
   AND (COLUMN_NAME LIKE '%TIME' OR COLUMN_NAME LIKE '%USER'
        OR COLUMN_NAME LIKE '%_AT' OR COLUMN_NAME LIKE '%_BY')
 ORDER BY TABLE_NAME, COLUMN_ID;

SELECT TABLE_NAME, COLUMN_NAME, DATA_LENGTH, CHAR_LENGTH, CHAR_USED
  FROM DBA_TAB_COLUMNS
 WHERE OWNER = 'DMSMGR' AND TABLE_NAME IN
       ('TQP_MAPCFG','TQP_PARASPEC','TQP_MAPDEF','TQP_GDS_MAP_REV','TQP_GDS_CHAIN')
   AND COLUMN_NAME IN ('CREATE_USER','UPDATE_USER','INSERT_USER')
 ORDER BY TABLE_NAME, COLUMN_NAME;
EXIT
