-- Verify legacy-style audit column names/types on the 13 new GDS tables.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET PAGESIZE 100 LINESIZE 160 FEEDBACK ON
COLUMN CHECK_NAME FORMAT A34
SELECT 'GDS_TABLES' CHECK_NAME, COUNT(*) ACTUAL_COUNT
  FROM DBA_TABLES WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
UNION ALL
SELECT 'LEGACY_TQP_TABLES', COUNT(*)
  FROM DBA_TABLES WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_%'
   AND TABLE_NAME NOT LIKE 'TQP_GDS_%'
UNION ALL
SELECT 'AUDIT_DATE_COLUMNS', COUNT(*)
  FROM DBA_TAB_COLUMNS WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
   AND COLUMN_NAME IN ('CREATE_TIME','UPDATE_TIME','COMMIT_TIME','RETIRE_TIME')
   AND DATA_TYPE = 'DATE'
UNION ALL
SELECT 'AUDIT_USER_COLUMNS', COUNT(*)
  FROM DBA_TAB_COLUMNS WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
   AND COLUMN_NAME IN ('CREATE_USER','UPDATE_USER')
   AND DATA_TYPE = 'VARCHAR2' AND DATA_LENGTH = 30 AND CHAR_USED = 'B'
UNION ALL
SELECT 'OLD_AUDIT_NAMES', COUNT(*)
  FROM DBA_TAB_COLUMNS WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
   AND COLUMN_NAME IN ('CREATED_AT','UPDATED_AT','CREATED_BY','UPDATED_BY',
                       'COMMITTED_AT','RETIRED_AT','EDITED_AT','EDITED_BY')
ORDER BY 1;

SELECT CONSTRAINT_TYPE, STATUS, VALIDATED, COUNT(*) CONSTRAINT_COUNT
  FROM DBA_CONSTRAINTS WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
 GROUP BY CONSTRAINT_TYPE, STATUS, VALIDATED ORDER BY CONSTRAINT_TYPE;
SELECT STATUS, COUNT(*) INDEX_COUNT FROM DBA_INDEXES
 WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
 GROUP BY STATUS;
EXIT
