-- DMSMGR: GDS Map / Chain 스키마 - 리비전 관리 제거, Factory + Device(제품) 1:1
-- 작성: 2026-10-02 Claude (CLAUDE-017) / 사용자 결정: "리비전 관리 하지 말자. factory, 제품에 1:1로 종속",
--       "키를 Factory + Device로 변경", "기존 데이터가 있으면 삭제 후 재등록만"
-- 변경 요약
--  - 헤더 TQP_GDS_MAP_REV -> TQP_GDS_MAP (PK FACTORY + DEVICE_ID, 상태 DRAFT / READY, REVISION_CODE 없음)
--  - LAYER / SOURCE_EL / PLACED_EL / CHAIN 6개: 키 MAP_REV_SEQ -> FACTORY + DEVICE_ID
--  - IMPORT_JOB: IMPORT_JOB_SEQ(시퀀스) 유지, Device당 1건(UQ_GDS_IMPORT_MAP)
--  - TQP_GDS_MAP_ACTIVE 테이블 / MAP_REV_SEQ 시퀀스 제거
--  - 모든 FK ON DELETE CASCADE: TQP_GDS_MAP 한 건을 지우면 그 Device의 도형 / 원본 / Layer / 저장 작업 / Chain이 함께 지워진다.
--    (BSL은 큰 테이블 PLACED / SOURCE를 먼저 명시적으로 지운 뒤 헤더를 지운다)
-- 나머지 컬럼 / 제약은 2026-10-02 로컬 DB(시퀀스 키 버전)에서 DBMS_METADATA로 추출한 정의 그대로다.
-- 주의: 기존 TQP_GDS_* 테이블과 데이터를 모두 삭제하고 다시 만든다. 시험 DB 전용.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET ECHO OFF FEEDBACK ON

-- 1) 기존 테이블 삭제 (자식 -> 부모 순서)
DROP TABLE DMSMGR.TQP_GDS_CHAIN_EDIT PURGE;
DROP TABLE DMSMGR.TQP_GDS_CHAIN_RULE PURGE;
DROP TABLE DMSMGR.TQP_GDS_CHAIN_LAYER PURGE;
DROP TABLE DMSMGR.TQP_GDS_CHAIN_MEMBER PURGE;
DROP TABLE DMSMGR.TQP_GDS_CHAIN_VER PURGE;
DROP TABLE DMSMGR.TQP_GDS_CHAIN PURGE;
DROP TABLE DMSMGR.TQP_GDS_IMPORT_BATCH PURGE;
DROP TABLE DMSMGR.TQP_GDS_IMPORT_JOB PURGE;
DROP TABLE DMSMGR.TQP_GDS_PLACED_EL PURGE;
DROP TABLE DMSMGR.TQP_GDS_SOURCE_EL PURGE;
DROP TABLE DMSMGR.TQP_GDS_LAYER PURGE;
DROP TABLE DMSMGR.TQP_GDS_MAP_ACTIVE PURGE;
DROP TABLE DMSMGR.TQP_GDS_MAP_REV PURGE;

-- 2) 사용하지 않는 시퀀스 삭제 (IMPORT_JOB_SEQ / CHAIN_SEQ / BATCH_EDIT_SEQ는 유지)
DROP SEQUENCE DMSMGR.MAP_REV_SEQ;

-- 3) 테이블 생성 (부모 -> 자식 순서)
CREATE TABLE "DMSMGR"."TQP_GDS_MAP"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"TOP_STRUCTURE" VARCHAR2(256 CHAR) NOT NULL ENABLE,
	"GDS_FILE_NAME" VARCHAR2(260 CHAR),
	"GDS_SHA256" CHAR(64) NOT NULL ENABLE,
	"USER_UNIT" BINARY_DOUBLE NOT NULL ENABLE,
	"DATABASE_UNIT" BINARY_DOUBLE NOT NULL ENABLE,
	"ID_GENERATOR_VERSION" NUMBER(6,0) DEFAULT 1 NOT NULL ENABLE,
	"POINTS_FORMAT_VERSION" NUMBER(6,0) DEFAULT 1 NOT NULL ENABLE,
	"SOURCE_PAYLOAD_VERSION" NUMBER(6,0) DEFAULT 1 NOT NULL ENABLE,
	"MAP_STATUS" VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(30),
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(30),
	"UPDATE_TIME" DATE,
	 CONSTRAINT "CK_GDS_MAP_STATUS" CHECK (MAP_STATUS IN ('DRAFT','READY')) ENABLE,
	 CONSTRAINT "CK_GDS_MAP_FMT" CHECK (ID_GENERATOR_VERSION > 0 AND POINTS_FORMAT_VERSION > 0 AND SOURCE_PAYLOAD_VERSION > 0) ENABLE,
	 CONSTRAINT "PK_GDS_MAP" PRIMARY KEY ("FACTORY", "DEVICE_ID")
  USING INDEX ENABLE
   ) ;

CREATE TABLE "DMSMGR"."TQP_GDS_LAYER"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"LAYER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"COLOR_ARGB" NUMBER(10,0) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(100 CHAR),
	 CONSTRAINT "PK_GDS_LAYER" PRIMARY KEY ("FACTORY", "DEVICE_ID", "LAYER_ID")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_LAYER_MAP" FOREIGN KEY ("FACTORY", "DEVICE_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_MAP" ("FACTORY", "DEVICE_ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_SOURCE_EL"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"SOURCE_ELEMENT_ID" VARCHAR2(512 CHAR) NOT NULL ENABLE,
	"STRUCTURE_NAME" VARCHAR2(256 CHAR) NOT NULL ENABLE,
	"SOURCE_ORDINAL" NUMBER(12,0) NOT NULL ENABLE,
	"ELEMENT_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"LAYER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"DATA_TYPE" NUMBER(10,0) NOT NULL ENABLE,
	"PARSER_DUPLICATE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"SOURCE_PAYLOAD_VERSION" NUMBER(6,0) NOT NULL ENABLE,
	"SOURCE_PAYLOAD_BIN" BLOB NOT NULL ENABLE,
	 CONSTRAINT "CK_GDS_SOURCE_DUP" CHECK (PARSER_DUPLICATE IN (0,1)) ENABLE,
	 CONSTRAINT "CK_GDS_SOURCE_FMT" CHECK (SOURCE_PAYLOAD_VERSION > 0) ENABLE,
	 CONSTRAINT "CK_GDS_SOURCE_ORD" CHECK (SOURCE_ORDINAL >= 0) ENABLE,
	 CONSTRAINT "PK_GDS_SOURCE_EL" PRIMARY KEY ("FACTORY", "DEVICE_ID", "SOURCE_ELEMENT_ID")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_SOURCE_MAP" FOREIGN KEY ("FACTORY", "DEVICE_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_MAP" ("FACTORY", "DEVICE_ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_PLACED_EL"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"PLACED_ELEMENT_ID" VARCHAR2(1024) NOT NULL ENABLE,
	"SOURCE_ELEMENT_ID" VARCHAR2(512 CHAR) NOT NULL ENABLE,
	"LAYER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"DATA_TYPE" NUMBER(10,0) NOT NULL ENABLE,
	"ELEMENT_TYPE" VARCHAR2(20) NOT NULL ENABLE,
	"CLOSED_FLAG" NUMBER(1,0) NOT NULL ENABLE,
	"PATH_WIDTH" BINARY_DOUBLE,
	"PATH_TYPE" NUMBER(3,0),
	"MIN_X" BINARY_DOUBLE NOT NULL ENABLE,
	"MIN_Y" BINARY_DOUBLE NOT NULL ENABLE,
	"MAX_X" BINARY_DOUBLE NOT NULL ENABLE,
	"MAX_Y" BINARY_DOUBLE NOT NULL ENABLE,
	"POINT_COUNT" NUMBER(12,0) NOT NULL ENABLE,
	"POINTS_FORMAT_VERSION" NUMBER(6,0) NOT NULL ENABLE,
	"POINTS_BIN" BLOB NOT NULL ENABLE,
	"TEXT_VALUE" CLOB,
	"TEXT_TYPE" NUMBER(10,0),
	"TEXT_FONT" NUMBER(10,0),
	"TEXT_HORIZONTAL" VARCHAR2(20),
	"TEXT_VERTICAL" VARCHAR2(20),
	 CONSTRAINT "CK_GDS_PLACED_TYPE" CHECK (ELEMENT_TYPE IN ('BOUNDARY','PATH','TEXT')) ENABLE,
	 CONSTRAINT "CK_GDS_PLACED_CLOSED" CHECK (CLOSED_FLAG IN (0,1)) ENABLE,
	 CONSTRAINT "CK_GDS_PLACED_POINTS" CHECK (POINT_COUNT > 0 AND POINTS_FORMAT_VERSION > 0) ENABLE,
	 CONSTRAINT "CK_GDS_PLACED_BOUNDS" CHECK (MIN_X <= MAX_X AND MIN_Y <= MAX_Y) ENABLE,
	 CONSTRAINT "CK_GDS_PLACED_PATHTYPE" CHECK ((ELEMENT_TYPE = 'PATH' AND PATH_TYPE BETWEEN 0 AND 255) OR (ELEMENT_TYPE <> 'PATH' AND PATH_TYPE IS NULL)) ENABLE,
	 CONSTRAINT "PK_GDS_PLACED_EL" PRIMARY KEY ("FACTORY", "DEVICE_ID", "PLACED_ELEMENT_ID")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_PLACED_SOURCE" FOREIGN KEY ("FACTORY", "DEVICE_ID", "SOURCE_ELEMENT_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_SOURCE_EL" ("FACTORY", "DEVICE_ID", "SOURCE_ELEMENT_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FK_GDS_PLACED_LAYER" FOREIGN KEY ("FACTORY", "DEVICE_ID", "LAYER_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_LAYER" ("FACTORY", "DEVICE_ID", "LAYER_ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_IMPORT_JOB"
   (	"IMPORT_JOB_SEQ" NUMBER NOT NULL ENABLE,
	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"JOB_STATUS" VARCHAR2(20) DEFAULT 'UPLOADING' NOT NULL ENABLE,
	"EXPECTED_SOURCE_COUNT" NUMBER(12,0) NOT NULL ENABLE,
	"EXPECTED_PLACED_COUNT" NUMBER(12,0) NOT NULL ENABLE,
	"EXPECTED_POINT_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"RECEIVED_SOURCE_COUNT" NUMBER(12,0) DEFAULT 0 NOT NULL ENABLE,
	"RECEIVED_PLACED_COUNT" NUMBER(12,0) DEFAULT 0 NOT NULL ENABLE,
	"RECEIVED_POINT_COUNT" NUMBER(18,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(30),
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(30),
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "CK_GDS_IMPORT_STATUS" CHECK (JOB_STATUS IN ('UPLOADING','VALIDATING','READY','FAILED','CANCELLED')) ENABLE,
	 CONSTRAINT "CK_GDS_IMPORT_COUNTS" CHECK (EXPECTED_SOURCE_COUNT >= 0 AND EXPECTED_PLACED_COUNT >= 0 AND EXPECTED_POINT_COUNT >= 0 AND RECEIVED_SOURCE_COUNT >= 0 AND RECEIVED_PLACED_COUNT >= 0 AND RECEIVED_POINT_COUNT >= 0) ENABLE,
	 CONSTRAINT "PK_GDS_IMPORT_JOB" PRIMARY KEY ("IMPORT_JOB_SEQ")
  USING INDEX ENABLE,
	 CONSTRAINT "UQ_GDS_IMPORT_MAP" UNIQUE ("FACTORY", "DEVICE_ID")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_IMPORT_MAP" FOREIGN KEY ("FACTORY", "DEVICE_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_MAP" ("FACTORY", "DEVICE_ID") ON DELETE CASCADE ENABLE
   ) ;

CREATE TABLE "DMSMGR"."TQP_GDS_IMPORT_BATCH"
   (	"IMPORT_JOB_SEQ" NUMBER NOT NULL ENABLE,
	"STREAM_KIND" VARCHAR2(10) NOT NULL ENABLE,
	"BATCH_NO" NUMBER(12,0) NOT NULL ENABLE,
	"FORMAT_VERSION" NUMBER(6,0) NOT NULL ENABLE,
	"PAYLOAD_SHA256" CHAR(64) NOT NULL ENABLE,
	"ITEM_COUNT" NUMBER(12,0) NOT NULL ENABLE,
	"POINT_COUNT" NUMBER(18,0) NOT NULL ENABLE,
	"PAYLOAD_BYTES" NUMBER(18,0) NOT NULL ENABLE,
	"COMMIT_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "CK_GDS_IMPORT_STREAM" CHECK (STREAM_KIND IN ('LAYER','SOURCE','PLACED')) ENABLE,
	 CONSTRAINT "CK_GDS_IMPORT_BATCH_NUM" CHECK (BATCH_NO >= 0 AND FORMAT_VERSION > 0 AND ITEM_COUNT > 0 AND POINT_COUNT >= 0 AND PAYLOAD_BYTES > 0) ENABLE,
	 CONSTRAINT "PK_GDS_IMPORT_BATCH" PRIMARY KEY ("IMPORT_JOB_SEQ", "STREAM_KIND", "BATCH_NO")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_IMPORT_BATCH_JOB" FOREIGN KEY ("IMPORT_JOB_SEQ")
	  REFERENCES "DMSMGR"."TQP_GDS_IMPORT_JOB" ("IMPORT_JOB_SEQ") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_CHAIN"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"CHAIN_SEQ" NUMBER NOT NULL ENABLE,
	"CHAIN_CODE" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CHAIN_STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(30),
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"RETIRE_TIME" DATE,
	"UPDATE_USER" VARCHAR2(30),
	"UPDATE_TIME" DATE,
	 CONSTRAINT "CK_GDS_CHAIN_STATUS" CHECK (CHAIN_STATUS IN ('ACTIVE','RETIRED')) ENABLE,
	 CONSTRAINT "PK_GDS_CHAIN" PRIMARY KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ")
  USING INDEX ENABLE,
	 CONSTRAINT "UQ_GDS_CHAIN_CODE" UNIQUE ("FACTORY", "DEVICE_ID", "CHAIN_CODE")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_MAP" FOREIGN KEY ("FACTORY", "DEVICE_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_MAP" ("FACTORY", "DEVICE_ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_CHAIN_VER"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"CHAIN_SEQ" NUMBER NOT NULL ENABLE,
	"VERSION_NO" NUMBER(10,0) NOT NULL ENABLE,
	"CHAIN_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE,
	"COLOR_ARGB" NUMBER(10,0) NOT NULL ENABLE,
	"APPLY_LAYER_RULES" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CELL_SIZE" NUMBER(18,4) NOT NULL ENABLE,
	"VERSION_STATUS" VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL ENABLE,
	"IS_CURRENT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(30),
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"UPDATE_USER" VARCHAR2(30),
	"UPDATE_TIME" DATE,
	 CONSTRAINT "CK_GDS_CHAIN_VER_NO" CHECK (VERSION_NO > 0) ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_VER_STATUS" CHECK (VERSION_STATUS IN ('DRAFT','READY','SUPERSEDED')) ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_VER_RULES" CHECK (APPLY_LAYER_RULES IN (0,1)) ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_VER_CURRENT" CHECK (IS_CURRENT IN (0,1) AND (IS_CURRENT = 0 OR VERSION_STATUS = 'READY')) ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_VER_CELL" CHECK (CELL_SIZE > 0) ENABLE,
	 CONSTRAINT "PK_GDS_CHAIN_VER" PRIMARY KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_VER_MASTER" FOREIGN KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ")
	  REFERENCES "DMSMGR"."TQP_GDS_CHAIN" ("FACTORY", "DEVICE_ID", "CHAIN_SEQ") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_CHAIN_MEMBER"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"CHAIN_SEQ" NUMBER NOT NULL ENABLE,
	"VERSION_NO" NUMBER(10,0) NOT NULL ENABLE,
	"PLACED_ELEMENT_ID" VARCHAR2(1024) NOT NULL ENABLE,
	"ROLE_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"INCLUSION_SOURCE" VARCHAR2(10) NOT NULL ENABLE,
	"MARKER_X" BINARY_DOUBLE,
	"MARKER_Y" BINARY_DOUBLE,
	 CONSTRAINT "CK_GDS_CHAIN_MEMBER_ROLE" CHECK (ROLE_CODE IN ('INPUT','OUTPUT','MEMBER')) ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_MEMBER_SRC" CHECK (INCLUSION_SOURCE IN ('TRACE','MANUAL','ENDPOINT')) ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_MEMBER_MARKER" CHECK ((ROLE_CODE IN ('INPUT','OUTPUT') AND MARKER_X IS NOT NULL AND MARKER_Y IS NOT NULL)
	 OR (ROLE_CODE = 'MEMBER' AND MARKER_X IS NULL AND MARKER_Y IS NULL)) ENABLE,
	 CONSTRAINT "PK_GDS_CHAIN_MEMBER" PRIMARY KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO", "PLACED_ELEMENT_ID")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_MEMBER_VER" FOREIGN KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO")
	  REFERENCES "DMSMGR"."TQP_GDS_CHAIN_VER" ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_MEMBER_EL" FOREIGN KEY ("FACTORY", "DEVICE_ID", "PLACED_ELEMENT_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_PLACED_EL" ("FACTORY", "DEVICE_ID", "PLACED_ELEMENT_ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_CHAIN_LAYER"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"CHAIN_SEQ" NUMBER NOT NULL ENABLE,
	"VERSION_NO" NUMBER(10,0) NOT NULL ENABLE,
	"LAYER_ID" NUMBER(10,0) NOT NULL ENABLE,
	 CONSTRAINT "PK_GDS_CHAIN_LAYER" PRIMARY KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO", "LAYER_ID")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_LAYER_VER" FOREIGN KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO")
	  REFERENCES "DMSMGR"."TQP_GDS_CHAIN_VER" ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_LAYER_MAP" FOREIGN KEY ("FACTORY", "DEVICE_ID", "LAYER_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_LAYER" ("FACTORY", "DEVICE_ID", "LAYER_ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_CHAIN_RULE"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"CHAIN_SEQ" NUMBER NOT NULL ENABLE,
	"VERSION_NO" NUMBER(10,0) NOT NULL ENABLE,
	"FIRST_LAYER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"SECOND_LAYER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"TOLERANCE" BINARY_DOUBLE NOT NULL ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_RULE_PAIR" CHECK (FIRST_LAYER_ID <= SECOND_LAYER_ID) ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_RULE_TOL" CHECK (TOLERANCE >= 0) ENABLE,
	 CONSTRAINT "PK_GDS_CHAIN_RULE" PRIMARY KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO", "FIRST_LAYER_ID", "SECOND_LAYER_ID")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_RULE_VER" FOREIGN KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO")
	  REFERENCES "DMSMGR"."TQP_GDS_CHAIN_VER" ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_RULE_L1" FOREIGN KEY ("FACTORY", "DEVICE_ID", "FIRST_LAYER_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_LAYER" ("FACTORY", "DEVICE_ID", "LAYER_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_RULE_L2" FOREIGN KEY ("FACTORY", "DEVICE_ID", "SECOND_LAYER_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_LAYER" ("FACTORY", "DEVICE_ID", "LAYER_ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "DMSMGR"."TQP_GDS_CHAIN_EDIT"
   (	"FACTORY" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"DEVICE_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"CHAIN_SEQ" NUMBER NOT NULL ENABLE,
	"VERSION_NO" NUMBER(10,0) NOT NULL ENABLE,
	"EDIT_SEQ" NUMBER(12,0) NOT NULL ENABLE,
	"PLACED_ELEMENT_ID" VARCHAR2(1024) NOT NULL ENABLE,
	"ACTION_CODE" VARCHAR2(10) NOT NULL ENABLE,
	"BATCH_EDIT_SEQ" NUMBER,
	"CREATE_USER" VARCHAR2(30),
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_EDIT_ACTION" CHECK (ACTION_CODE IN ('ADD','EXCLUDE','RESTORE')) ENABLE,
	 CONSTRAINT "CK_GDS_CHAIN_EDIT_SEQ" CHECK (EDIT_SEQ > 0) ENABLE,
	 CONSTRAINT "PK_GDS_CHAIN_EDIT" PRIMARY KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO", "EDIT_SEQ")
  USING INDEX ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_EDIT_VER" FOREIGN KEY ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO")
	  REFERENCES "DMSMGR"."TQP_GDS_CHAIN_VER" ("FACTORY", "DEVICE_ID", "CHAIN_SEQ", "VERSION_NO") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FK_GDS_CHAIN_EDIT_EL" FOREIGN KEY ("FACTORY", "DEVICE_ID", "PLACED_ELEMENT_ID")
	  REFERENCES "DMSMGR"."TQP_GDS_PLACED_EL" ("FACTORY", "DEVICE_ID", "PLACED_ELEMENT_ID") ON DELETE CASCADE ENABLE
   );

-- 4) 조회 / 제약 인덱스
CREATE INDEX "DMSMGR"."IX_GDS_PLACED_LAYER" ON "DMSMGR"."TQP_GDS_PLACED_EL" ("FACTORY", "DEVICE_ID", "LAYER_ID", "PLACED_ELEMENT_ID");
CREATE INDEX "DMSMGR"."IX_GDS_PLACED_SOURCE" ON "DMSMGR"."TQP_GDS_PLACED_EL" ("FACTORY", "DEVICE_ID", "SOURCE_ELEMENT_ID");
CREATE INDEX "DMSMGR"."IX_GDS_CHAIN_MEMBER_EL" ON "DMSMGR"."TQP_GDS_CHAIN_MEMBER" ("FACTORY", "DEVICE_ID", "PLACED_ELEMENT_ID", "CHAIN_SEQ", "VERSION_NO");
CREATE INDEX "DMSMGR"."IX_GDS_CHAIN_EDIT_EL" ON "DMSMGR"."TQP_GDS_CHAIN_EDIT" ("FACTORY", "DEVICE_ID", "PLACED_ELEMENT_ID", "CHAIN_SEQ", "VERSION_NO");
-- Chain당 현재 버전은 최대 1개
CREATE UNIQUE INDEX "DMSMGR"."UX_GDS_CHAIN_CURRENT" ON "DMSMGR"."TQP_GDS_CHAIN_VER"
    (CASE "IS_CURRENT" WHEN 1 THEN "FACTORY" END, CASE "IS_CURRENT" WHEN 1 THEN "DEVICE_ID" END, CASE "IS_CURRENT" WHEN 1 THEN "CHAIN_SEQ" END);
-- Chain 버전당 INPUT 1개 / OUTPUT 최대 1개
CREATE UNIQUE INDEX "DMSMGR"."UX_GDS_CHAIN_ENDPOINT" ON "DMSMGR"."TQP_GDS_CHAIN_MEMBER"
    (CASE "ROLE_CODE" WHEN 'INPUT' THEN "FACTORY" WHEN 'OUTPUT' THEN "FACTORY" END,
     CASE "ROLE_CODE" WHEN 'INPUT' THEN "DEVICE_ID" WHEN 'OUTPUT' THEN "DEVICE_ID" END,
     CASE "ROLE_CODE" WHEN 'INPUT' THEN "CHAIN_SEQ" WHEN 'OUTPUT' THEN "CHAIN_SEQ" END,
     CASE "ROLE_CODE" WHEN 'INPUT' THEN "VERSION_NO" WHEN 'OUTPUT' THEN "VERSION_NO" END,
     CASE "ROLE_CODE" WHEN 'INPUT' THEN "ROLE_CODE" WHEN 'OUTPUT' THEN "ROLE_CODE" END);

EXIT
