-- Read-only gate before creating the TQP_GDS_* objects in DMSMGR.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET PAGESIZE 100 LINESIZE 160 FEEDBACK OFF
SELECT SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME,
       SYS_CONTEXT('USERENV','CON_NAME') AS CON_NAME FROM DUAL;
SELECT COUNT(*) AS EXISTING_GDS_OBJECTS
  FROM DBA_OBJECTS
 WHERE OWNER = 'DMSMGR'
   AND (OBJECT_NAME LIKE 'TQP_GDS_%' OR OBJECT_NAME LIKE 'PK_GDS_%'
        OR OBJECT_NAME LIKE 'FK_GDS_%' OR OBJECT_NAME LIKE 'IX_GDS_%'
        OR OBJECT_NAME LIKE 'UX_GDS_%' OR OBJECT_NAME LIKE 'UQ_GDS_%');
SELECT COUNT(*) AS EXISTING_GDS_CONSTRAINTS
  FROM DBA_CONSTRAINTS
 WHERE OWNER = 'DMSMGR'
   AND (CONSTRAINT_NAME LIKE 'PK_GDS_%' OR CONSTRAINT_NAME LIKE 'FK_GDS_%'
        OR CONSTRAINT_NAME LIKE 'UQ_GDS_%' OR CONSTRAINT_NAME LIKE 'CK_GDS_%');
EXIT
