-- Read-only verification for newly created DMSMGR TQP_GDS_* tables.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET PAGESIZE 100 LINESIZE 180 FEEDBACK ON
COLUMN TABLE_NAME FORMAT A30
COLUMN INDEX_NAME FORMAT A30
COLUMN STATUS FORMAT A10
SELECT TABLE_NAME FROM DBA_TABLES
 WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
 ORDER BY TABLE_NAME;
SELECT CONSTRAINT_TYPE, STATUS, VALIDATED, COUNT(*) AS CONSTRAINT_COUNT
  FROM DBA_CONSTRAINTS
 WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
 GROUP BY CONSTRAINT_TYPE, STATUS, VALIDATED
 ORDER BY CONSTRAINT_TYPE, STATUS, VALIDATED;
SELECT INDEX_NAME, STATUS FROM DBA_INDEXES
 WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_GDS_%'
   AND INDEX_NAME LIKE '%GDS_%'
 ORDER BY INDEX_NAME;
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
  FROM DBA_TAB_COLUMNS
 WHERE OWNER = 'DMSMGR'
   AND ((TABLE_NAME = 'TQP_GDS_PLACED_EL' AND COLUMN_NAME IN ('PATH_TYPE','POINTS_BIN'))
        OR (TABLE_NAME = 'TQP_GDS_CHAIN_MEMBER' AND COLUMN_NAME IN ('ROLE_CODE','PLACED_ELEMENT_ID')))
 ORDER BY TABLE_NAME, COLUMN_NAME;
SELECT COUNT(*) AS EXISTING_TQP_TABLE_COUNT FROM DBA_TABLES
 WHERE OWNER = 'DMSMGR' AND TABLE_NAME LIKE 'TQP_%'
   AND TABLE_NAME NOT LIKE 'TQP_GDS_%';
SELECT 'TQP_GDS_MAP_REV' TABLE_NAME, COUNT(*) ROW_COUNT FROM DMSMGR.TQP_GDS_MAP_REV
UNION ALL SELECT 'TQP_GDS_MAP_ACTIVE', COUNT(*) FROM DMSMGR.TQP_GDS_MAP_ACTIVE
UNION ALL SELECT 'TQP_GDS_LAYER', COUNT(*) FROM DMSMGR.TQP_GDS_LAYER
UNION ALL SELECT 'TQP_GDS_SOURCE_EL', COUNT(*) FROM DMSMGR.TQP_GDS_SOURCE_EL
UNION ALL SELECT 'TQP_GDS_PLACED_EL', COUNT(*) FROM DMSMGR.TQP_GDS_PLACED_EL
UNION ALL SELECT 'TQP_GDS_IMPORT_JOB', COUNT(*) FROM DMSMGR.TQP_GDS_IMPORT_JOB
UNION ALL SELECT 'TQP_GDS_IMPORT_BATCH', COUNT(*) FROM DMSMGR.TQP_GDS_IMPORT_BATCH
UNION ALL SELECT 'TQP_GDS_CHAIN', COUNT(*) FROM DMSMGR.TQP_GDS_CHAIN
UNION ALL SELECT 'TQP_GDS_CHAIN_VER', COUNT(*) FROM DMSMGR.TQP_GDS_CHAIN_VER
UNION ALL SELECT 'TQP_GDS_CHAIN_MEMBER', COUNT(*) FROM DMSMGR.TQP_GDS_CHAIN_MEMBER
UNION ALL SELECT 'TQP_GDS_CHAIN_LAYER', COUNT(*) FROM DMSMGR.TQP_GDS_CHAIN_LAYER
UNION ALL SELECT 'TQP_GDS_CHAIN_RULE', COUNT(*) FROM DMSMGR.TQP_GDS_CHAIN_RULE
UNION ALL SELECT 'TQP_GDS_CHAIN_EDIT', COUNT(*) FROM DMSMGR.TQP_GDS_CHAIN_EDIT
ORDER BY 1;
EXIT
