-- DMSMGR / MESMGR: GDS Map schema, phase 1.
-- Creates new TQP_GDS_* objects only. Never rerun against existing objects.
-- No data load or changes to legacy TQP_MAPDEF/TQP_PRODUCT.
-- Audit columns match common legacy TQP DATE/VARCHAR2(30 BYTE) properties.
-- Service must set UPDATE_TIME/UPDATE_USER on every update; a DEFAULT covers INSERT only.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET ECHO OFF FEEDBACK ON

CREATE TABLE DMSMGR.TQP_GDS_MAP_REV (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    FACTORY VARCHAR2(30 BYTE) NOT NULL,
    DEVICE_ID VARCHAR2(50 CHAR) NOT NULL,
    REVISION_CODE VARCHAR2(100 CHAR) NOT NULL,
    TOP_STRUCTURE VARCHAR2(256 CHAR) NOT NULL,
    GDS_SHA256 CHAR(64 BYTE) NOT NULL,
    USER_UNIT BINARY_DOUBLE NOT NULL,
    DATABASE_UNIT BINARY_DOUBLE NOT NULL,
    ID_GENERATOR_VERSION NUMBER(6) DEFAULT 1 NOT NULL,
    POINTS_FORMAT_VERSION NUMBER(6) DEFAULT 1 NOT NULL,
    PLACED_BATCH_FORMAT_VERSION NUMBER(6) DEFAULT 2 NOT NULL,
    REVISION_STATUS VARCHAR2(20 BYTE) DEFAULT 'DRAFT' NOT NULL,
    CREATE_USER VARCHAR2(30 BYTE),
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER VARCHAR2(30 BYTE),
    UPDATE_TIME DATE,
    CONSTRAINT PK_GDS_MAP_REV PRIMARY KEY (MAP_REVISION_ID),
    CONSTRAINT UQ_GDS_MAP_REV_CODE UNIQUE (FACTORY, DEVICE_ID, REVISION_CODE),
    CONSTRAINT UQ_GDS_MAP_REV_DEVICE UNIQUE (FACTORY, DEVICE_ID, MAP_REVISION_ID),
    CONSTRAINT CK_GDS_MAP_REV_STATUS CHECK (REVISION_STATUS IN ('DRAFT','READY','RETIRED')),
    CONSTRAINT CK_GDS_MAP_REV_FMT CHECK (ID_GENERATOR_VERSION > 0 AND POINTS_FORMAT_VERSION > 0 AND PLACED_BATCH_FORMAT_VERSION > 0)
);

CREATE TABLE DMSMGR.TQP_GDS_MAP_ACTIVE (
    FACTORY VARCHAR2(30 BYTE) NOT NULL,
    DEVICE_ID VARCHAR2(50 CHAR) NOT NULL,
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    CREATE_USER VARCHAR2(30 BYTE),
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER VARCHAR2(30 BYTE),
    UPDATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_GDS_MAP_ACTIVE PRIMARY KEY (FACTORY, DEVICE_ID),
    CONSTRAINT FK_GDS_MAP_ACTIVE_REV FOREIGN KEY (FACTORY, DEVICE_ID, MAP_REVISION_ID)
        REFERENCES DMSMGR.TQP_GDS_MAP_REV (FACTORY, DEVICE_ID, MAP_REVISION_ID)
);

CREATE TABLE DMSMGR.TQP_GDS_LAYER (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    LAYER_ID NUMBER(10) NOT NULL,
    COLOR_ARGB NUMBER(10) NOT NULL,
    DISPLAY_NAME VARCHAR2(100 CHAR),
    CONSTRAINT PK_GDS_LAYER PRIMARY KEY (MAP_REVISION_ID, LAYER_ID),
    CONSTRAINT FK_GDS_LAYER_REV FOREIGN KEY (MAP_REVISION_ID)
        REFERENCES DMSMGR.TQP_GDS_MAP_REV (MAP_REVISION_ID)
);

CREATE TABLE DMSMGR.TQP_GDS_SOURCE_EL (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    SOURCE_ELEMENT_ID VARCHAR2(512 CHAR) NOT NULL,
    STRUCTURE_NAME VARCHAR2(256 CHAR) NOT NULL,
    SOURCE_ORDINAL NUMBER(12) NOT NULL,
    ELEMENT_TYPE VARCHAR2(20 BYTE) NOT NULL,
    LAYER_ID NUMBER(10) NOT NULL,
    DATA_TYPE NUMBER(10) NOT NULL,
    PARSER_DUPLICATE NUMBER(1) DEFAULT 0 NOT NULL,
    SOURCE_PAYLOAD_VERSION NUMBER(6) NOT NULL,
    SOURCE_PAYLOAD_BIN BLOB NOT NULL,
    CONSTRAINT PK_GDS_SOURCE_EL PRIMARY KEY (MAP_REVISION_ID, SOURCE_ELEMENT_ID),
    CONSTRAINT FK_GDS_SOURCE_REV FOREIGN KEY (MAP_REVISION_ID)
        REFERENCES DMSMGR.TQP_GDS_MAP_REV (MAP_REVISION_ID),
    CONSTRAINT CK_GDS_SOURCE_DUP CHECK (PARSER_DUPLICATE IN (0,1)),
    CONSTRAINT CK_GDS_SOURCE_FMT CHECK (SOURCE_PAYLOAD_VERSION > 0),
    CONSTRAINT CK_GDS_SOURCE_ORD CHECK (SOURCE_ORDINAL >= 0)
);

CREATE TABLE DMSMGR.TQP_GDS_PLACED_EL (
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    PLACED_ELEMENT_ID VARCHAR2(1024 BYTE) NOT NULL,
    SOURCE_ELEMENT_ID VARCHAR2(512 CHAR) NOT NULL,
    LAYER_ID NUMBER(10) NOT NULL,
    DATA_TYPE NUMBER(10) NOT NULL,
    ELEMENT_TYPE VARCHAR2(20 BYTE) NOT NULL,
    CLOSED_FLAG NUMBER(1) NOT NULL,
    PATH_WIDTH BINARY_DOUBLE,
    PATH_TYPE NUMBER(3),
    MIN_X BINARY_DOUBLE NOT NULL,
    MIN_Y BINARY_DOUBLE NOT NULL,
    MAX_X BINARY_DOUBLE NOT NULL,
    MAX_Y BINARY_DOUBLE NOT NULL,
    POINT_COUNT NUMBER(12) NOT NULL,
    POINTS_FORMAT_VERSION NUMBER(6) NOT NULL,
    POINTS_BIN BLOB NOT NULL,
    TEXT_VALUE CLOB,
    TEXT_TYPE NUMBER(10),
    TEXT_FONT NUMBER(10),
    TEXT_HORIZONTAL VARCHAR2(20 BYTE),
    TEXT_VERTICAL VARCHAR2(20 BYTE),
    CONSTRAINT PK_GDS_PLACED_EL PRIMARY KEY (MAP_REVISION_ID, PLACED_ELEMENT_ID),
    CONSTRAINT FK_GDS_PLACED_SOURCE FOREIGN KEY (MAP_REVISION_ID, SOURCE_ELEMENT_ID)
        REFERENCES DMSMGR.TQP_GDS_SOURCE_EL (MAP_REVISION_ID, SOURCE_ELEMENT_ID),
    CONSTRAINT FK_GDS_PLACED_LAYER FOREIGN KEY (MAP_REVISION_ID, LAYER_ID)
        REFERENCES DMSMGR.TQP_GDS_LAYER (MAP_REVISION_ID, LAYER_ID),
    CONSTRAINT CK_GDS_PLACED_TYPE CHECK (ELEMENT_TYPE IN ('BOUNDARY','PATH','TEXT')),
    CONSTRAINT CK_GDS_PLACED_CLOSED CHECK (CLOSED_FLAG IN (0,1)),
    CONSTRAINT CK_GDS_PLACED_POINTS CHECK (POINT_COUNT > 0 AND POINTS_FORMAT_VERSION > 0),
    CONSTRAINT CK_GDS_PLACED_BOUNDS CHECK (MIN_X <= MAX_X AND MIN_Y <= MAX_Y),
    CONSTRAINT CK_GDS_PLACED_PATHTYPE CHECK ((ELEMENT_TYPE = 'PATH' AND PATH_TYPE BETWEEN 0 AND 255) OR (ELEMENT_TYPE <> 'PATH' AND PATH_TYPE IS NULL))
);

CREATE INDEX DMSMGR.IX_GDS_PLACED_SOURCE ON DMSMGR.TQP_GDS_PLACED_EL
    (MAP_REVISION_ID, SOURCE_ELEMENT_ID);
CREATE INDEX DMSMGR.IX_GDS_PLACED_LAYER ON DMSMGR.TQP_GDS_PLACED_EL
    (MAP_REVISION_ID, LAYER_ID, PLACED_ELEMENT_ID);

CREATE TABLE DMSMGR.TQP_GDS_IMPORT_JOB (
    JOB_ID VARCHAR2(36 BYTE) NOT NULL,
    MAP_REVISION_ID VARCHAR2(36 BYTE) NOT NULL,
    JOB_STATUS VARCHAR2(20 BYTE) DEFAULT 'UPLOADING' NOT NULL,
    EXPECTED_SOURCE_COUNT NUMBER(12) NOT NULL,
    EXPECTED_PLACED_COUNT NUMBER(12) NOT NULL,
    EXPECTED_POINT_COUNT NUMBER(18) NOT NULL,
    RECEIVED_SOURCE_COUNT NUMBER(12) DEFAULT 0 NOT NULL,
    RECEIVED_PLACED_COUNT NUMBER(12) DEFAULT 0 NOT NULL,
    RECEIVED_POINT_COUNT NUMBER(18) DEFAULT 0 NOT NULL,
    CREATE_USER VARCHAR2(30 BYTE),
    CREATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER VARCHAR2(30 BYTE),
    UPDATE_TIME DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_GDS_IMPORT_JOB PRIMARY KEY (JOB_ID),
    CONSTRAINT UQ_GDS_IMPORT_REV UNIQUE (MAP_REVISION_ID),
    CONSTRAINT FK_GDS_IMPORT_REV FOREIGN KEY (MAP_REVISION_ID)
        REFERENCES DMSMGR.TQP_GDS_MAP_REV (MAP_REVISION_ID),
    CONSTRAINT CK_GDS_IMPORT_STATUS CHECK (JOB_STATUS IN ('UPLOADING','VALIDATING','READY','FAILED','CANCELLED')),
    CONSTRAINT CK_GDS_IMPORT_COUNTS CHECK (EXPECTED_SOURCE_COUNT >= 0 AND EXPECTED_PLACED_COUNT >= 0 AND EXPECTED_POINT_COUNT >= 0 AND RECEIVED_SOURCE_COUNT >= 0 AND RECEIVED_PLACED_COUNT >= 0 AND RECEIVED_POINT_COUNT >= 0)
);

CREATE TABLE DMSMGR.TQP_GDS_IMPORT_BATCH (
    JOB_ID VARCHAR2(36 BYTE) NOT NULL,
    STREAM_KIND VARCHAR2(10 BYTE) NOT NULL,
    BATCH_NO NUMBER(12) NOT NULL,
    FORMAT_VERSION NUMBER(6) NOT NULL,
    PAYLOAD_SHA256 CHAR(64 BYTE) NOT NULL,
    ITEM_COUNT NUMBER(12) NOT NULL,
    POINT_COUNT NUMBER(18) NOT NULL,
    PAYLOAD_BYTES NUMBER(18) NOT NULL,
    COMMIT_TIME DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_GDS_IMPORT_BATCH PRIMARY KEY (JOB_ID, STREAM_KIND, BATCH_NO),
    CONSTRAINT FK_GDS_IMPORT_BATCH_JOB FOREIGN KEY (JOB_ID)
        REFERENCES DMSMGR.TQP_GDS_IMPORT_JOB (JOB_ID),
    CONSTRAINT CK_GDS_IMPORT_STREAM CHECK (STREAM_KIND IN ('LAYER','SOURCE','PLACED')),
    CONSTRAINT CK_GDS_IMPORT_BATCH_NUM CHECK (BATCH_NO >= 0 AND FORMAT_VERSION > 0 AND ITEM_COUNT > 0 AND POINT_COUNT >= 0 AND PAYLOAD_BYTES > 0)
);

EXIT
