/**************************************************************************
 *
 *       COPYRIGHT (C) 1993  by  KEITHLEY INSTRUMENTS, INC.
 *       Cleveland, Ohio
 *
 *       This software is furnished under a license and may
 *       be used and copied only in accordance with the terms
 *       of such license, and with the inclusion of the above
 *       COPYRIGHT notice.  This software or any other copies
 *       thereof may not be provided or otherwise made
 *       available to any other person.  No title to and
 *       ownership of the software is hereby transferred.
 *       The information in this software is subject to
 *       change without notice, and should not be construed
 *       as a commitment by KEITHLEY INSTRUMENTS, INC.
 *
 *       KEITHLEY assumes no responsibility for the use or
 *       reliability of its software on equipment which is
 *       not supplied by KEITHLEY.
 *
 **************************************************************************
  Module Name: COM_usrlib.h


  Description: This module contains the headers for the usrlib wrapper
  	functions generated by KULT for the use of KITT.  It also contains
  	the function prototypes for handling results generated by usrlib
  	functions.
  	
  	It contains #def's for ALL wrappers in KITT and usrlibs.  This file
  	is included by ksox_def.h!

 **************************************************************************
 *
 * File:     $Source: /cm/test/build/S600/v420/COMMON/RCS/COM_usrlib.h,v $
 * Current $Revision: 1.20 $
 * Curent     $State: REL $
 * Last Rev    $Date: 1998/06/04 12:59:34 $
 *
 * Change       $Log: COM_usrlib.h,v $
 * Change       Revision 1.20  1998/06/04 12:59:34  williamson
 * Change       PR 5043 5599 if-else support
 * Change
 * Change       Revision 1.19  1998/06/03 14:09:39  williamson
 * Change       PR 5043  IF support
 * Change
 * Change       Revision 1.18  1998/03/12 16:12:53  williamson
 * Change       PR 5701  #if'd out the definition of TRUE, FALSE.  kdf.h takes care of these
 * Change
 * Change       Revision 1.17  1998/03/05 13:57:51  williamson
 * Change       PR 6061 Added code for TSF support.
 * Change
 * Change       Revision 1.16  1997/11/19 14:39:32  williamson
 * Change       Added some #if stuff to squelch the compiler warnings about L and C being
 * Change       redefined...
 * Change
 * Change       Revision 1.15  1997/10/27 17:12:10  moore
 * Change       NT code cleanup
 * Change
 * Change       Revision 1.14  1997/09/09 15:12:38  kdev
 * Change       Add ktemalloc.h
 * Change
 * Change       Revision 1.13  1997/08/28 17:50:06  aujla
 * Change       Updated with the NT changes.
 * Change
 * Change       Revision 1.12  1997/03/10 15:00:19  jain
 * Change        PR3290, 3293 added error checking for the number of points passed for sweep functions.
 * Change
 * Revision 1.11  1997/01/08  21:43:42  jain
 * PR507 changes for removing the 32 parameter limit.
 *
 * Revision 1.10  1996/12/04  14:53:21  williamson
 * Adding HASH functionality...look for ljl comments for changes
 *
 * Revision 1.9  1996/07/23  15:00:00  jain
 *  PR1815 added define for KULT_max_output_strlen.
 *
 * Revision 1.8  1996/05/08  15:00:09  witzke
 * PR1293 updated for kte30 added data types
 *
 * Revision 1.7  1995/11/27  15:57:43  witzke
 * PR1203 added define of NULL
 *
 * Revision 1.6  1995/08/10  15:08:47  tufte
 * pr520 adds support for arrays and doubles to KULT/KITT etc
 *
 * Revision 1.5  1995/08/02  14:09:04  tufte
 * pr520 add DOUBLE, DBL_ARRAY, INT_ARRAY types to KITT/KULT
 *
 * Revision 1.4  1995/07/11  21:40:36  tufte
 * PR00549 add user function to result_info_t struct
 *
 * Revision 1.3  1994/08/04  13:57:00  szanto
 * Added plot and log fields to result_info_t.  These were mysteriously omitted when we had
 * to headers with this struct.
 *
 * Revision 1.2  1994/08/04  13:39:47  szanto
 * Corrected typo of stlib to stdlib
 *
 * Revision 1.1  1994/08/04  13:33:41  szanto
 * Initial revision
 *
 *************************************************************************/

#ifndef _COM_USRLIB_H
#define _COM_USRLIB_H
#ifdef WIN32
/* This file is included in all wrapper functions of USRLIB */
/* Add new defines for c files which includes this file*/
#include "ktemalloc.h"
#endif
#include <stdio.h>
#include <stdlib.h>

#define KULT_max_output_strlen 256

/*
 * Be careful when changing MAXPARMS; other parts of the code must
 * be changed at the same time (code related to the parameter text edit
 * and text area widgets; search for "changing MAXPARMS" in *.c
 * to find the areas that must be changed).
 */

#define MAXPARMS    32      /* max # of parms a function may have */


/* PR 5701  Make true/false definition consistant.  kdf.h defines these,
 * we don't really need them here..
 */
#if 0
#ifndef	TRUE
#define TRUE 1
#define FALSE 0
#endif /*!TRUE*/
#endif



/* possible values for parm_type */
#define SINGLE_VALUE    0   /* "scalar" */
#define ARRAY           1   /* multiple values */
#define INT             2   /* int, call by value */
#define INT_P           3   /* int, call by reference */
#define LONG            4
#define LONG_P          5
#define FLOAT           6
#define FLOAT_P         7
#define CHAR            8
#define CHAR_P          9
#define STRING          10
#define DOUBLE			11
#define DOUBLE_P		12
/**
#define DBL_ARRAY		13
#define INT_ARRAY		14
**/
#define D_ARRAY_T		15
#define DOUBLE_ARRAY		15
#define I_ARRAY_T		16
#define INT_ARRAY		16
#define F_ARRAY_T		17
#define FLOAT_ARRAY		17
#define	L_ARRAY_T		18
#define LONG_ARRAY		18
#define NO_TYPE			19
#define IDENTIFIER		20

#ifdef TESTSOFT
#define ARGTYPE_INT INT
#endif

typedef struct _result_info
{
	char *function_name;		/* e.g. "measv" */
	char *result_name;			/* "tag"; could be anything */
	int result_type;			/* LONG, LONG_P, FLOAT, FLOAT_P, etc. */
	void *resultp;				/* pointer to the result */
	int	num_items;				/* number of elements at resultp */
	int	sweepable;
	int log;
	int plot;
	int user;
        struct _result_info *nextp;	/* link to next element in list */
  	struct _result_info *nexth;	/* link to next hash  ljl */
} result_info_t;

/* callinfo_t -- all wrapper functions have the same parameter:
 * a pointer to the callinfo_t struct.
 */

typedef struct _callinfo_t
{
	char *retval_name;
	char **parms;
} callinfo_t;


#if !((defined _MSDOS) || (defined WIN32))

/* PARM_ERR() always returns 0 (for later cast to int, long, float, or char *)
 * the last expression in a comma-separated list of expressions is the
 * value of the entire list.
 */

#define PARM_ERR(x) (outputf("Error: missing parameter #%d\n", (x)), 0)

/* macros to do some error checking on the parms[x] string,
 * and provide a short way to write atoi(parms[x]) etc.
 * this scheme takes a lot of code space, but it's practically bulletproof
 *
 * If there is an error (a null string is passed in),
 * these macros return 0 cast to the proper type and print an error
 * message.
 */
#define I(x)    (callinfo->parms[(x)] != NULL ? atoi(callinfo->parms[(x)]) : (int)PARM_ERR(x))

#ifdef L
#undef L
#endif
#define L(x)    (callinfo->parms[(x)] != NULL ? atol(callinfo->parms[(x)]) : (long)PARM_ERR(x))

#define F(x)    (callinfo->parms[(x)] != NULL ? (float) atof(callinfo->parms[(x)]) : (float)PARM_ERR(x))

#define D(x)    (callinfo->parms[(x)] != NULL ? (double) atof(callinfo->parms[(x)]) : (double)PARM_ERR(x))

#define S(x)    (callinfo->parms[(x)] != NULL ? callinfo->parms[(x)] : (char *)PARM_ERR(x))

#ifdef C
#undef C
#endif
#define C(x)    (callinfo->parms[(x)] != NULL ? callinfo->parms[(x)][0] : (char)PARM_ERR(x))

#else /*!_MSDOS*/

#ifdef WIN32
#ifdef L
#undef L
#endif
#ifdef C
#undef C
#endif
#endif

#define	I(x)	atoi(callinfo->parms[(x)]) 
#define	L(x)	atol(callinfo->parms[(x)]) 
/* Added for double DEV */
#define D(x)    (double) atof(callinfo->parms[(x)])
#define	F(x)	atof(callinfo->parms[(x)]) 
#define	S(x)	callinfo->parms[(x)] 
#define	C(x)	callinfo->parms[(x)][0]

#endif /*!_MSDOS*/

#define	RETVAL_NAME	(callinfo->retval_name)

#define RP_ERROR 10
#define SWEEP_ERROR -1

#define NO_IF_FOUND -20
#define IF_STATEMENT_TRUE -21
#define IF_STATEMENT_FALSE -22
#define IF_STATEMENT_ELSE -23


/*
 *	Include a few prototypes moved here from ksox_pro.h.  These are the
 *	prototypes REQUIRED to build the wrapper correctly!
 */

void			add_result(char *function_name, char *result_name, int
					result_type, void *resultp, int num_items);

#endif /* ! _COM_USRLIB_H */
