# DACrux Configuration ini file
# Create Time 2019-05-13 11:23_33
# Service port define of DACrux's Application module
[APPLICATION UNIT]
MIRACOM_QMS_COMMON = 7510
MIRACOM_DACRUX_RMS = 7511
MIRACOM_DACRUX_PMS = 7512
MIRACOM_DACRUX_PRB = 7513
MIRACOM_DACRUX_PKG = 7514
MIRACOM_DACRUX_DMS = 7515
MIRACOM_DACRUX_PCM = 7516
MIRACOM_DACRUX_SPC = 7517
MIRACOM_DACRUX_TMS = 7518
MIRACOM_DACRUX_YMS = 7519
MIRACOM_EMS_DA = 7520
MIRACOM_EMS_DAOPER = 7521
MIRACOM_EMS_WB = 7522
MIRACOM_EMS_DP = 7523
MIRACOM_EMS_ENGUI = 7530

[CONFIG MODE]
# Method of Application Configuration
# Default 
# CONFIG_STOCK = Registry
# Configuration mode has two option that "Registry" or "INIFile"
CONFIG_STOCK = INIFile

[LAST OPTION]
UserID = 
ServerIP = Localhost
EAIServerIP = Localhost
EAIServerPort = 10101
EAIChannel = /QMS
Language = English
LanguageFile = Global.Lng
Site = 
Factory = 
FactoryList = 
RibbonMenuEnable = False
