-- Device 기준 Map 저장을 위한 신규 테이블 초안이다.
-- 기존 GDS_ELEMENT는 수정하지 않는다. 실제 Device 마스터 키/권한 확인 뒤 적용한다.
-- 이 파일은 실행하지 않은 설계 산출물이며 Chain 테이블은 다음 단계에서 추가한다.
-- 대량 전송은 DRAFT 개정본에 배치별로 적재하고, 검증 후 READY로 전환한다.

-- 한 Device의 도면 개정본을 구분한다. 같은 Device에 여러 Revision을 허용한다.
CREATE TABLE DEVICE_MAP_REVISION (
    MAP_REVISION_ID VARCHAR2(36 CHAR) NOT NULL,
    DEVICE_ID VARCHAR2(100 CHAR) NOT NULL,
    REVISION_CODE VARCHAR2(100 CHAR) NOT NULL,
    TOP_STRUCTURE VARCHAR2(256 CHAR) NOT NULL,
    GDS_SHA256 CHAR(64 CHAR) NOT NULL,
    USER_UNIT BINARY_DOUBLE NOT NULL,
    DATABASE_UNIT BINARY_DOUBLE NOT NULL,
    ID_GENERATOR_VERSION NUMBER(6) DEFAULT 1 NOT NULL,
    GEOMETRY_FORMAT_VERSION NUMBER(6) DEFAULT 1 NOT NULL,
    REVISION_STATUS VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DEVICE_MAP_REV PRIMARY KEY (MAP_REVISION_ID),
    CONSTRAINT UQ_DEVICE_MAP_REV UNIQUE (DEVICE_ID, REVISION_CODE),
    CONSTRAINT CK_DEVICE_MAP_STATUS CHECK (REVISION_STATUS IN ('DRAFT', 'READY', 'RETIRED'))
);

-- 원본 Grid 행은 배치 도형과 별도로 보관한다. PAYLOAD_BIN의 직렬화 계약은 저장 코드에서 버전별로 정의한다.
CREATE TABLE MAP_SOURCE_ELEMENT (
    MAP_REVISION_ID VARCHAR2(36 CHAR) NOT NULL,
    SOURCE_ELEMENT_ID VARCHAR2(512 CHAR) NOT NULL,
    STRUCTURE_NAME VARCHAR2(256 CHAR) NOT NULL,
    ELEMENT_TYPE VARCHAR2(20 CHAR) NOT NULL,
    LAYER_ID NUMBER(10) NOT NULL,
    DATA_TYPE NUMBER(10) NOT NULL,
    PARSER_DUPLICATE NUMBER(1) DEFAULT 0 NOT NULL,
    PAYLOAD_VERSION NUMBER(6) NOT NULL,
    PAYLOAD_BIN BLOB NOT NULL,
    CONSTRAINT PK_MAP_SOURCE_EL PRIMARY KEY (MAP_REVISION_ID, SOURCE_ELEMENT_ID),
    CONSTRAINT FK_MAP_SOURCE_REV FOREIGN KEY (MAP_REVISION_ID)
        REFERENCES DEVICE_MAP_REVISION (MAP_REVISION_ID),
    CONSTRAINT CK_MAP_SOURCE_DUP CHECK (PARSER_DUPLICATE IN (0, 1))
);

-- Map의 기본색은 Revision별로 저장한다. 화면의 임시 Layer 체크 상태와 구분한다.
CREATE TABLE MAP_LAYER (
    MAP_REVISION_ID VARCHAR2(36 CHAR) NOT NULL,
    LAYER_ID NUMBER(10) NOT NULL,
    COLOR_ARGB NUMBER(10) NOT NULL,
    CONSTRAINT PK_MAP_LAYER PRIMARY KEY (MAP_REVISION_ID, LAYER_ID),
    CONSTRAINT FK_MAP_LAYER_REV FOREIGN KEY (MAP_REVISION_ID)
        REFERENCES DEVICE_MAP_REVISION (MAP_REVISION_ID)
);

-- 월드 좌표로 펼친 전체 도형을 저장한다. Chain에 없는 도형도 포함해야 DB만으로 Map을 그릴 수 있다.
-- POINTS_BIN 형식 v1: 각 점의 X/Y를 IEEE 754 64-bit little-endian으로 순서대로 기록한다.
-- BOUNDARY/PATH/TEXT 모두 POINT_COUNT와 POINTS_BIN을 보유한다. TEXT는 삽입점 한 개다.
CREATE TABLE MAP_PLACED_ELEMENT (
    MAP_REVISION_ID VARCHAR2(36 CHAR) NOT NULL,
    PLACED_ELEMENT_ID VARCHAR2(1024 CHAR) NOT NULL,
    SOURCE_ELEMENT_ID VARCHAR2(512 CHAR) NOT NULL,
    LAYER_ID NUMBER(10) NOT NULL,
    DATA_TYPE NUMBER(10) NOT NULL,
    ELEMENT_TYPE VARCHAR2(20 CHAR) NOT NULL,
    CLOSED_FLAG NUMBER(1) NOT NULL,
    PATH_WIDTH BINARY_DOUBLE,
    MIN_X BINARY_DOUBLE NOT NULL,
    MIN_Y BINARY_DOUBLE NOT NULL,
    MAX_X BINARY_DOUBLE NOT NULL,
    MAX_Y BINARY_DOUBLE NOT NULL,
    POINT_COUNT NUMBER(10) NOT NULL,
    POINTS_BIN BLOB NOT NULL,
    TEXT_VALUE CLOB,
    TEXT_TYPE NUMBER(10),
    TEXT_FONT NUMBER(10),
    TEXT_HORIZONTAL VARCHAR2(20 CHAR),
    TEXT_VERTICAL VARCHAR2(20 CHAR),
    CONSTRAINT PK_MAP_PLACED_EL PRIMARY KEY (MAP_REVISION_ID, PLACED_ELEMENT_ID),
    CONSTRAINT FK_MAP_PLACED_SOURCE FOREIGN KEY (MAP_REVISION_ID, SOURCE_ELEMENT_ID)
        REFERENCES MAP_SOURCE_ELEMENT (MAP_REVISION_ID, SOURCE_ELEMENT_ID),
    CONSTRAINT FK_MAP_PLACED_LAYER FOREIGN KEY (MAP_REVISION_ID, LAYER_ID)
        REFERENCES MAP_LAYER (MAP_REVISION_ID, LAYER_ID),
    CONSTRAINT CK_MAP_PLACED_CLOSED CHECK (CLOSED_FLAG IN (0, 1)),
    CONSTRAINT CK_MAP_PLACED_COUNT CHECK (POINT_COUNT > 0)
);

-- Grid 원본 -> 배치 인스턴스 조회와 Layer 단위 Map 로딩을 지원한다.
CREATE INDEX IX_MAP_PLACED_SOURCE ON MAP_PLACED_ELEMENT (MAP_REVISION_ID, SOURCE_ELEMENT_ID);
CREATE INDEX IX_MAP_PLACED_LAYER ON MAP_PLACED_ELEMENT (MAP_REVISION_ID, LAYER_ID);

-- Service 업로드 한 건의 전체 진행 상태를 보관한다. 재시도해도 같은 JOB_ID를 사용한다.
CREATE TABLE MAP_IMPORT_JOB (
    JOB_ID VARCHAR2(36 CHAR) NOT NULL,
    MAP_REVISION_ID VARCHAR2(36 CHAR) NOT NULL,
    JOB_STATUS VARCHAR2(20 CHAR) DEFAULT 'UPLOADING' NOT NULL,
    EXPECTED_SOURCE_COUNT NUMBER(12) NOT NULL,
    EXPECTED_PLACED_COUNT NUMBER(12) NOT NULL,
    EXPECTED_POINT_COUNT NUMBER(18) NOT NULL,
    RECEIVED_SOURCE_COUNT NUMBER(12) DEFAULT 0 NOT NULL,
    RECEIVED_PLACED_COUNT NUMBER(12) DEFAULT 0 NOT NULL,
    RECEIVED_POINT_COUNT NUMBER(18) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MAP_IMPORT_JOB PRIMARY KEY (JOB_ID),
    CONSTRAINT FK_MAP_IMPORT_REV FOREIGN KEY (MAP_REVISION_ID)
        REFERENCES DEVICE_MAP_REVISION (MAP_REVISION_ID),
    CONSTRAINT UQ_MAP_IMPORT_REV UNIQUE (MAP_REVISION_ID),
    CONSTRAINT CK_MAP_IMPORT_STATUS CHECK
        (JOB_STATUS IN ('UPLOADING', 'VALIDATING', 'READY', 'FAILED', 'CANCELLED'))
);

-- 배치 응답 유실 뒤 같은 내용을 다시 보내도 중복 INSERT하지 않도록 배치 번호/해시를 기록한다.
CREATE TABLE MAP_IMPORT_BATCH (
    JOB_ID VARCHAR2(36 CHAR) NOT NULL,
    STREAM_KIND VARCHAR2(10 CHAR) NOT NULL,
    BATCH_NO NUMBER(12) NOT NULL,
    FORMAT_VERSION NUMBER(6) NOT NULL,
    PAYLOAD_SHA256 CHAR(64 CHAR) NOT NULL,
    ITEM_COUNT NUMBER(12) NOT NULL,
    POINT_COUNT NUMBER(18) NOT NULL,
    PAYLOAD_BYTES NUMBER(18) NOT NULL,
    COMMITTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MAP_IMPORT_BATCH PRIMARY KEY (JOB_ID, STREAM_KIND, BATCH_NO),
    CONSTRAINT FK_MAP_IMPORT_BATCH_JOB FOREIGN KEY (JOB_ID)
        REFERENCES MAP_IMPORT_JOB (JOB_ID),
    CONSTRAINT CK_MAP_IMPORT_STREAM CHECK (STREAM_KIND IN ('LAYER', 'SOURCE', 'PLACED'))
);
